const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00009
  { name: "CT Scan Brain", category: "CT Scan", price: 1600, sample_type: "Imaging" },
  { name: "CT SCAN BRAIN WITH CONTRAST", category: "CT Scan", price: 2200, sample_type: "Imaging" },
  { name: "CT Scan Brain with Mastoids", category: "CT Scan", price: 4900, sample_type: "Imaging" },
  { name: "CT Scan Brain with Orbit", category: "CT Scan", price: 5100, sample_type: "Imaging" },
  { name: "CT Scan Brain with PNS", category: "CT Scan", price: 5100, sample_type: "Imaging" },
  { name: "CT Scan Brain with Sella Turcica", category: "CT Scan", price: 1400, sample_type: "Imaging" },
  { name: "CT Scan Brain with Sinus", category: "CT Scan", price: 5100, sample_type: "Imaging" },
  { name: "CT Scan Cervical Spine (IV Contrast)", category: "CT Scan", price: 5000, sample_type: "Imaging" },
  { name: "CT Scan Cervical Spine (Myelogram)", category: "CT Scan", price: 4000, sample_type: "Imaging" },
  { name: "CT Scan Cervical Spine (Plain)", category: "CT Scan", price: 4000, sample_type: "Imaging" },
  { name: "CT Scan Chest", category: "CT Scan", price: 4200, sample_type: "Imaging" },
  { name: "CT Scan D11 TO L1", category: "CT Scan", price: 2600, sample_type: "Imaging" },
  { name: "CT Scan D12 TO L5", category: "CT Scan", price: 2600, sample_type: "Imaging" },
  { name: "CT Scan D12 TO S2", category: "CT Scan", price: 2600, sample_type: "Imaging" },
  { name: "CT Scan D7 TO L2", category: "CT Scan", price: 2600, sample_type: "Imaging" },
  { name: "CT Scan Elbow", category: "CT Scan", price: 3500, sample_type: "Imaging" },
  { name: "CT Scan FACE with Neck", category: "CT Scan", price: 4500, sample_type: "Imaging" },
  { name: "CT Scan Hip Joint with IV Contrast", category: "CT Scan", price: 3500, sample_type: "Imaging" },
  { name: "CT Scan Hips with Pelvis", category: "CT Scan", price: 2600, sample_type: "Imaging" },
  { name: "CT Scan HRCT (Lungs Only)", category: "CT Scan", price: 3300, sample_type: "Imaging" },
  { name: "CT Scan Kidney", category: "CT Scan", price: 4500, sample_type: "Imaging" },
  { name: "CT Scan Kidney (Left/Right)", category: "CT Scan", price: 4100, sample_type: "Imaging" },
  { name: "CT Scan Knee Joint", category: "CT Scan", price: 3500, sample_type: "Imaging" },
  { name: "CT Scan KUB", category: "CT Scan", price: 4500, sample_type: "Imaging" },
  { name: "CT Scan L S Spine Including Coccyx", category: "CT Scan", price: 2600, sample_type: "Imaging" },
  { name: "CT Scan L1 TO T12", category: "CT Scan", price: 2600, sample_type: "Imaging" },
  { name: "CT Scan Larynx", category: "CT Scan", price: 3500, sample_type: "Imaging" },

  // Image 00010
  { name: "CT Scan Leg", category: "CT Scan", price: 2600, sample_type: "Imaging" },
  { name: "CT Scan Liver / Single Organ", category: "CT Scan", price: 4100, sample_type: "Imaging" },
  { name: "CT Scan Lower Abdomen", category: "CT Scan", price: 4500, sample_type: "Imaging" },
  { name: "CT Scan Lower Dorsal, lumber Spine", category: "CT Scan", price: 5200, sample_type: "Imaging" },
  { name: "CT Scan Lumber Spine (Plain)", category: "CT Scan", price: 2600, sample_type: "Imaging" },
  { name: "CT Scan Mandible", category: "CT Scan", price: 3500, sample_type: "Imaging" },
  { name: "CT Scan Mastoids", category: "CT Scan", price: 2600, sample_type: "Imaging" },
  { name: "CT Scan Nasopharynx", category: "CT Scan", price: 3500, sample_type: "Imaging" },
  { name: "CT Scan Nasopharynx & Soft Tissue", category: "CT Scan", price: 3500, sample_type: "Imaging" },
  { name: "CT Scan Neck", category: "CT Scan", price: 3500, sample_type: "Imaging" },
  { name: "CT Scan Orbit", category: "CT Scan", price: 3500, sample_type: "Imaging" },
  { name: "CT Scan Orbit & PNS", category: "CT Scan", price: 6900, sample_type: "Imaging" },
  { name: "CT Scan Pelvis", category: "CT Scan", price: 4100, sample_type: "Imaging" },
  { name: "CT Scan Pituitary Fossa", category: "CT Scan", price: 2000, sample_type: "Imaging" },
  { name: "CT Scan PNS (Para Nasal Sinuses)", category: "CT Scan", price: 3000, sample_type: "Imaging" },
  { name: "CT Scan Right Sterno Clavicular Joint", category: "CT Scan", price: 2600, sample_type: "Imaging" },
  { name: "CT Scan Temporal Bone", category: "CT Scan", price: 3300, sample_type: "Imaging" },
  { name: "CT Scan Thorax", category: "CT Scan", price: 3500, sample_type: "Imaging" },
  { name: "CT Scan TM Joint", category: "CT Scan", price: 3500, sample_type: "Imaging" },
  { name: "CT Scan Upper Abdomen", category: "CT Scan", price: 4500, sample_type: "Imaging" },
  { name: "CT Scan Whole Abdomen", category: "CT Scan", price: 6200, sample_type: "Imaging" },
  { name: "CT Scan Whole Dorsal Spine (IV Contrast)", category: "CT Scan", price: 6000, sample_type: "Imaging" },
  { name: "CT (Clotting Time)", category: "Hematology", price: 50, sample_type: "Blood" },
  { name: "Culture for G.N.D", category: "Microbiology", price: 200, sample_type: "Urine/Vaginal Swab" },
  { name: "Culture for K.L.B", category: "Microbiology", price: 200, sample_type: "Throat Swab" },
  { name: "Cysticircosis Antibody / Taenia solium", category: "Serology", price: 550, sample_type: "Serum" },
  { name: "Cytomegalovirus (CMV) IgG", category: "Serology", price: 500, sample_type: "Serum" }
];

importBatch(tests).then(() => process.exit());
