const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00045
  { name: "USG Parotid Gland", category: "USG", price: 600, sample_type: "N/A" },
  { name: "USG Pelvis", category: "USG", price: 850, sample_type: "N/A" },
  { name: "USG Pelvis (Screening)", category: "USG", price: 400, sample_type: "N/A" },
  { name: "USG Penis", category: "USG", price: 1150, sample_type: "N/A" },
  { name: "USG Popliteal Fossa", category: "USG", price: 550, sample_type: "N/A" },
  { name: "USG Pregnancy", category: "USG", price: 600, sample_type: "N/A" },
  { name: "USG Pregnancy (TVS)", category: "USG", price: 1500, sample_type: "N/A" },
  { name: "USG Pregnancy with Color Doppler Study", category: "USG", price: 1650, sample_type: "N/A" },
  { name: "USG Pregnancy with Color Doppler Study Twin", category: "USG", price: 3300, sample_type: "N/A" },
  { name: "USG Prostate", category: "USG", price: 450, sample_type: "N/A" },
  { name: "USG Right Tendo Achites", category: "USG", price: 550, sample_type: "N/A" },
  { name: "USG Scrotal Sac", category: "USG", price: 1150, sample_type: "N/A" },
  { name: "USG Scrotum", category: "USG", price: 1150, sample_type: "N/A" },
  { name: "USG Shoulder", category: "USG", price: 1150, sample_type: "N/A" },
  { name: "USG Single Organ", category: "USG", price: 550, sample_type: "N/A" },
  { name: "USG Soft tissue", category: "USG", price: 600, sample_type: "N/A" },
  { name: "USG Sono-Salpingography", category: "USG", price: 1500, sample_type: "N/A" },
  { name: "USG STUDY OF BOTH LOWER LIMBS", category: "USG", price: 6800, sample_type: "N/A" },
  { name: "USG Swelling Over Back Side", category: "USG", price: 300, sample_type: "N/A" },
  { name: "USG Testis", category: "USG", price: 1400, sample_type: "N/A" },
  { name: "USG Testis (Screening)", category: "USG", price: 950, sample_type: "N/A" },
  { name: "USG Thigh", category: "USG", price: 1150, sample_type: "N/A" },
  { name: "USG Thorax", category: "USG", price: 1150, sample_type: "N/A" },
  { name: "USG Thyroid Gland", category: "USG", price: 1150, sample_type: "N/A" },
  { name: "USG Thyroid Gland (Doppler Study)", category: "USG", price: 1600, sample_type: "N/A" },
  { name: "USG Trans Rectal", category: "USG", price: 850, sample_type: "N/A" },

  // Image 00046
  { name: "USG Upper Abdomen", category: "USG", price: 850, sample_type: "N/A" },
  { name: "USG Upper Abdomen (Doppler Study)", category: "USG", price: 1200, sample_type: "N/A" },
  { name: "USG Whole Abdomen", category: "USG", price: 1050, sample_type: "N/A" },
  { name: "USG Whole Abdomen (Screening)", category: "USG", price: 750, sample_type: "N/A" },
  { name: "USG Wrist Joint", category: "USG", price: 600, sample_type: "N/A" },
  { name: "USGPortable", category: "USG", price: 1500, sample_type: "N/A" },
  { name: "US-TSH (Ultra Sensitive TSH)", category: "Biochemistry", price: 300, sample_type: "Blood" },
  { name: "Vaccine after Blood Allergy-Introducing Direct P...", category: "Other", price: 2000, sample_type: "Blood" },
  { name: "Vaginal / Cervical swab", category: "Microbiology", price: 250, sample_type: "Swab" },
  { name: "Vaginal Smear for PAP Stain", category: "Other", price: 350, sample_type: "Swab" },
  { name: "Vaginal Swab AFB Stain", category: "Microbiology", price: 80, sample_type: "Swab" },
  { name: "Vaginal Swab Culture", category: "Microbiology", price: 0, sample_type: "Swab" },
  { name: "Vaginal Swab for AFB Stain", category: "Microbiology", price: 80, sample_type: "Swab" },
  { name: "Vaginal Swab for Fram Stain", category: "Microbiology", price: 70, sample_type: "Swab" },
  { name: "Vaginal Swab Gram Stain", category: "Microbiology", price: 70, sample_type: "Swab" },
  { name: "Vaginal Swab RE (Hanging Drop + Gram Stain)", category: "Microbiology", price: 250, sample_type: "Swab" },
  { name: "Valporic Acid (Sodium valproate)", category: "Biochemistry", price: 600, sample_type: "Blood" },
  { name: "Vanden Burgh Reaction", category: "Biochemistry", price: 50, sample_type: "Blood" },
  { name: "VDRL", category: "Serology", price: 150, sample_type: "Blood" },
  { name: "VEP", category: "Other", price: 1000, sample_type: "N/A" },
  { name: "VERA", category: "Other", price: 1000, sample_type: "N/A" },
  { name: "Vitamin B12", category: "Biochemistry", price: 600, sample_type: "Blood" },
  { name: "Vitamin D Total - 25 OH", category: "Biochemistry", price: 1000, sample_type: "Blood" },
  { name: "VLDL-Cholesterol", category: "Biochemistry", price: 200, sample_type: "Blood" },
  { name: "Wasserman Test", category: "Serology", price: 100, sample_type: "Blood" }
];

importBatch(tests).then(() => process.exit());
