const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00023
  { name: "Factor VII Defficient", category: "Hematology", price: 100, sample_type: "Plasma" },
  { name: "Factor VIII Immunodepleted", category: "Hematology", price: 2000, sample_type: "Plasma" },
  { name: "FDP (Fibrinogen Degradation Product)", category: "Hematology", price: 600, sample_type: "Plasma" },
  { name: "Female Infertility Profile", category: "Profile", price: 1800, sample_type: "Serum" },
  { name: "Fern Test", category: "Clinical Pathology", price: 150, sample_type: "Cervical Mucus" },
  { name: "Ferritin", category: "Biochemistry", price: 550, sample_type: "Serum" },
  { name: "Fibrinogen", category: "Hematology", price: 500, sample_type: "Plasma" },
  { name: "Filaria (Wuchereria Bancrofti) Antigen", category: "Serology", price: 800, sample_type: "Serum" },
  { name: "Filaria Antigen", category: "Serology", price: 900, sample_type: "Serum" },
  { name: "Fluid Aspiration & Cytology", category: "Cytology", price: 700, sample_type: "Body Fluid" },
  { name: "FNAC Breast", category: "Cytology", price: 1000, sample_type: "FNAC" },
  { name: "FNAC Cervical", category: "Cytology", price: 1000, sample_type: "FNAC" },
  { name: "FNAC Deep Origin", category: "Cytology", price: 700, sample_type: "FNAC" },
  { name: "FNAC Forehead", category: "Cytology", price: 500, sample_type: "FNAC" },
  { name: "FNAC Liver", category: "Cytology", price: 500, sample_type: "FNAC" },
  { name: "FNAC Mandible", category: "Cytology", price: 700, sample_type: "FNAC" },
  { name: "FNAC Neck", category: "Cytology", price: 1000, sample_type: "FNAC" },
  { name: "FNAC Pancreas", category: "Cytology", price: 1000, sample_type: "FNAC" },
  { name: "FNAC Smear for Reporting", category: "Cytology", price: 1000, sample_type: "FNAC" },
  { name: "FNAC Subcutaneous Swelling", category: "Cytology", price: 1000, sample_type: "FNAC" },
  { name: "FNAC Submandibular", category: "Cytology", price: 1000, sample_type: "FNAC" },
  { name: "FNAC Supraclavicular Lymph", category: "Cytology", price: 1000, sample_type: "FNAC" },
  { name: "FNAC Thyroid Gland", category: "Cytology", price: 1000, sample_type: "FNAC" },
  { name: "Foetal Haemoglobin", category: "Hematology", price: 600, sample_type: "Whole Blood" },
  { name: "Foetal Haemoglobin by HPLC", category: "Hematology", price: 800, sample_type: "Whole Blood" },
  { name: "Folic Acid", category: "Biochemistry", price: 800, sample_type: "Serum" },
  { name: "Free Beta hCG", category: "Hormone", price: 650, sample_type: "Serum" },

  // Image 00024
  { name: "Free Beta hCG quantitative", category: "Hormone", price: 500, sample_type: "Serum" },
  { name: "Free Cholesterol", category: "Biochemistry", price: 100, sample_type: "Serum" },
  { name: "Free Estradiol", category: "Hormone", price: 700, sample_type: "Serum" },
  { name: "Free P S A", category: "Hormone", price: 600, sample_type: "Serum" },
  { name: "Free Testosterone", category: "Hormone", price: 600, sample_type: "Serum" },
  { name: "FSH & PRL", category: "Hormone", price: 800, sample_type: "Serum" },
  { name: "FSH (Follicle Stimulating Hormone)", category: "Hormone", price: 400, sample_type: "Serum" },
  { name: "FSH, LH & PRL", category: "Hormone", price: 1200, sample_type: "Serum" },
  { name: "FT3 & TSH", category: "Hormone", price: 700, sample_type: "Serum" },
  { name: "FT3 (Free Tri-iodothyronine)", category: "Hormone", price: 350, sample_type: "Serum" },
  { name: "FT3, FT4 & TSH", category: "Hormone", price: 1000, sample_type: "Serum" },
  { name: "FT4 & TSH", category: "Hormone", price: 700, sample_type: "Serum" },
  { name: "FT4 (Free Thyroxine)", category: "Hormone", price: 400, sample_type: "Serum" },
  { name: "Fungus Culture", category: "Microbiology", price: 350, sample_type: "Skin/Nail" },
  { name: "Fungus Culture & Sensitivity", category: "Microbiology", price: 250, sample_type: "Skin/Nail" },
  { name: "G6PD (Glucose-6-Phosphate Dehydrogenase)", category: "Biochemistry", price: 350, sample_type: "Serum" },
  { name: "Gastrin Level", category: "Hormone", price: 900, sample_type: "Serum" },
  { name: "General Health Check Up", category: "Profile", price: 2500, sample_type: "Various" },
  { name: "Genetic Counselling (Pre / Post Marital)", category: "Genetic", price: 2400, sample_type: "N/A" },
  { name: "GGT (Gamma GT)", category: "Biochemistry", price: 300, sample_type: "Serum" },
  { name: "GH (90 Minutes after Glucose)", category: "Hormone", price: 650, sample_type: "Serum" },
  { name: "GH (Fasting + Glucose)", category: "Hormone", price: 1000, sample_type: "Serum" },
  { name: "GH (Growth Hormone)", category: "Hormone", price: 500, sample_type: "Serum" },
  { name: "Globulin", category: "Biochemistry", price: 150, sample_type: "Serum" },
  { name: "Glucose Fasting", category: "Biochemistry", price: 50, sample_type: "Plasma" },
  { name: "Glucose PP (Post Prandial)", category: "Biochemistry", price: 50, sample_type: "Plasma" }
];

importBatch(tests).then(() => process.exit());
