const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00043
  { name: "USG Doppler Study of Portul Venies", category: "USG", price: 1200, sample_type: "N/A" },
  { name: "USG Doppler Study of Renal Arteries", category: "USG", price: 1200, sample_type: "N/A" },
  { name: "USG Doppler Study of Right Lower Limb", category: "USG", price: 1750, sample_type: "N/A" },
  { name: "USG Doppler Study of Right Upper Limb", category: "USG", price: 1750, sample_type: "N/A" },
  { name: "USG Doppler Study of Scrotal", category: "USG", price: 1200, sample_type: "N/A" },
  { name: "USG Eye (Both)", category: "USG", price: 2300, sample_type: "N/A" },
  { name: "USG Eye (Left / Right)", category: "USG", price: 1400, sample_type: "N/A" },
  { name: "USG Finger", category: "USG", price: 1150, sample_type: "N/A" },
  { name: "USG Foetal Anomaly Scan", category: "USG", price: 2000, sample_type: "N/A" },
  { name: "USG Foetal Anomaly Scan (Doppler Study)", category: "USG", price: 2700, sample_type: "N/A" },
  { name: "USG Foetal Anomaly Scan Twin", category: "USG", price: 3300, sample_type: "N/A" },
  { name: "USG Foetal Anomaly Scan Twin (Doppler)", category: "USG", price: 4500, sample_type: "N/A" },
  { name: "USG foetal Doppler Study", category: "USG", price: 1650, sample_type: "N/A" },
  { name: "USG Foetal Echocardiography", category: "USG", price: 2000, sample_type: "N/A" },
  { name: "USG Foetal Profile", category: "USG", price: 850, sample_type: "N/A" },
  { name: "USG FOETAL PROFILE WITH NT SCAN", category: "USG", price: 1050, sample_type: "N/A" },
  { name: "USG Follicular Study", category: "USG", price: 1750, sample_type: "N/A" },
  { name: "USG Follicular Study (Screening)", category: "USG", price: 500, sample_type: "N/A" },
  { name: "USG Follicularmetry", category: "USG", price: 2000, sample_type: "N/A" },
  { name: "USG Gall Bladder (Screening)", category: "USG", price: 350, sample_type: "N/A" },
  { name: "USG Guided Ascitic Fluid", category: "USG", price: 300, sample_type: "N/A" },
  { name: "USG Guided Aspiration", category: "USG", price: 750, sample_type: "N/A" },
  { name: "USG Guided Biopsy", category: "USG", price: 600, sample_type: "N/A" },
  { name: "USG Guided Fluid Aspiration", category: "USG", price: 500, sample_type: "N/A" },
  { name: "USG Gynae Profile", category: "USG", price: 350, sample_type: "N/A" },
  { name: "USG HBS (Hepato Biliary System)", category: "USG", price: 400, sample_type: "N/A" },

  // Image 00044
  { name: "USG Hemithorax", category: "USG", price: 550, sample_type: "N/A" },
  { name: "USG Hip (Left / Right)", category: "USG", price: 600, sample_type: "N/A" },
  { name: "USG Kidney", category: "USG", price: 600, sample_type: "N/A" },
  { name: "USG Knee (Both)", category: "USG", price: 1000, sample_type: "N/A" },
  { name: "USG Knee (Left / Right)", category: "USG", price: 1400, sample_type: "N/A" },
  { name: "USG KUB", category: "USG", price: 850, sample_type: "N/A" },
  { name: "USG KUB + Pelvis", category: "USG", price: 850, sample_type: "N/A" },
  { name: "USG KUB + Prostate", category: "USG", price: 750, sample_type: "N/A" },
  { name: "USG KUB dopplar", category: "USG", price: 1200, sample_type: "N/A" },
  { name: "USG Lip", category: "USG", price: 550, sample_type: "N/A" },
  { name: "USG Lower Abdomen", category: "USG", price: 850, sample_type: "N/A" },
  { name: "USG Lower Abdomen (TVS)", category: "USG", price: 1500, sample_type: "N/A" },
  { name: "USG Lower Abdomen with Sono Uret...", category: "USG", price: 400, sample_type: "N/A" },
  { name: "USG Lower Doppler Study", category: "USG", price: 1200, sample_type: "N/A" },
  { name: "USG Lump", category: "USG", price: 800, sample_type: "N/A" },
  { name: "USG Mass From Radical Artery", category: "USG", price: 600, sample_type: "N/A" },
  { name: "USG Mastoid", category: "USG", price: 1150, sample_type: "N/A" },
  { name: "USG Micturating Cysto Urethrogram", category: "USG", price: 600, sample_type: "N/A" },
  { name: "USG Neck", category: "USG", price: 1400, sample_type: "N/A" },
  { name: "USG Neonatal Brain", category: "USG", price: 600, sample_type: "N/A" },
  { name: "USG OF PARAUMBILLICAL AREA", category: "USG", price: 1150, sample_type: "N/A" },
  { name: "USG OF TVS", category: "USG", price: 1500, sample_type: "N/A" },
  { name: "USG Orbit", category: "USG", price: 1150, sample_type: "N/A" },
  { name: "USG Paravertebral Region", category: "USG", price: 550, sample_type: "N/A" }
];

importBatch(tests).then(() => process.exit());
