const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00027
  { name: "Hepatitis E Virus (HEV) Antibody IgG", category: "Serology", price: 650, sample_type: "Serum" },
  { name: "Hepatitis E Virus (HEV) Antibody IgM", category: "Serology", price: 500, sample_type: "Serum" },
  { name: "Herpes Simplex Virus- 2 (HSV-2) IgG", category: "Serology", price: 500, sample_type: "Serum" },
  { name: "Herpes Simplex Virus- 2 (HSV-2) IgM", category: "Serology", price: 800, sample_type: "Serum" },
  { name: "Herpes Simplex Virus-1(HSV-1) IgG", category: "Serology", price: 500, sample_type: "Serum" },
  { name: "Herpes Simplex Virus-1(HSV-1) IgM", category: "Serology", price: 300, sample_type: "Serum" },
  { name: "HEV Total (IgG + IgM)", category: "Serology", price: 1300, sample_type: "Serum" },
  { name: "Histology Biopsy Per Section", category: "Histopathology", price: 600, sample_type: "Tissue" },
  { name: "HIV I & II", category: "Serology", price: 450, sample_type: "Serum" },
  { name: "HLA B27", category: "Genetic", price: 2000, sample_type: "Whole Blood" },
  { name: "Holter Machine Hire", category: "Cardiology", price: 1800, sample_type: "N/A" },
  { name: "Homo cystine - Blood", category: "Biochemistry", price: 1500, sample_type: "Serum" },
  { name: "Homo cystine - Urine", category: "Biochemistry", price: 1500, sample_type: "Urine" },
  { name: "Hypertension Profile", category: "Profile", price: 1470, sample_type: "Serum" },
  { name: "Immunoglobulin (IgA) + (IgG) + (IgM)", category: "Biochemistry", price: 1500, sample_type: "Serum" },
  { name: "Immunoglobulin A - (IgA)", category: "Biochemistry", price: 500, sample_type: "Serum" },
  { name: "Immunoglobulin E - (IgE)", category: "Biochemistry", price: 600, sample_type: "Serum" },
  { name: "Immunoglobulin G - (IgG)", category: "Biochemistry", price: 500, sample_type: "Serum" },
  { name: "Immunoglobulin M - (IgM)", category: "Biochemistry", price: 500, sample_type: "Serum" },
  { name: "Immunoglobulin Profile", category: "Profile", price: 1200, sample_type: "Serum" },
  { name: "India Ink Preperation", category: "Microbiology", price: 100, sample_type: "Body Fluid" },
  { name: "Inorganic Phosphorus (Serum)", category: "Biochemistry", price: 200, sample_type: "Serum" },
  { name: "Inorganic Phosphorus (Urine)", category: "Biochemistry", price: 100, sample_type: "Urine" },
  { name: "Insulin (Each)", category: "Hormone", price: 400, sample_type: "Serum" },

  // Image 00028
  { name: "Insulin (Free)", category: "Hormone", price: 400, sample_type: "Serum" },
  { name: "Insulin (Midnight)", category: "Hormone", price: 400, sample_type: "Serum" },
  { name: "Iron", category: "Biochemistry", price: 250, sample_type: "Serum" },
  { name: "Iron & TIBC", category: "Biochemistry", price: 500, sample_type: "Serum" },
  { name: "Joint Fluid for AFB Stain", category: "Microbiology", price: 150, sample_type: "Joint Fluid" },
  { name: "Joint Fluid for Cell Count & Cell Type", category: "Clinical Pathology", price: 150, sample_type: "Joint Fluid" },
  { name: "Joint Fluid for Chloride", category: "Biochemistry", price: 150, sample_type: "Joint Fluid" },
  { name: "Joint Fluid for Gram Stain", category: "Microbiology", price: 150, sample_type: "Joint Fluid" },
  { name: "Joint Fluid for Protein", category: "Biochemistry", price: 150, sample_type: "Joint Fluid" },
  { name: "Joint Fluid for Specific Gravity", category: "Clinical Pathology", price: 150, sample_type: "Joint Fluid" },
  { name: "Joint Fluid for Sugar", category: "Biochemistry", price: 150, sample_type: "Joint Fluid" },
  { name: "Kahn Test", category: "Serology", price: 100, sample_type: "Serum" },
  { name: "Kalazar (Rapid Test)", category: "Serology", price: 500, sample_type: "Serum" },
  { name: "Karyotyping (Chromosomal Analysis)", category: "Genetic", price: 2800, sample_type: "Whole Blood" },
  { name: "Karyotyping with C-Banding", category: "Genetic", price: 2400, sample_type: "Whole Blood" },
  { name: "KFT/RFT(Kidney / Renal Function Test)", category: "Profile", price: 1070, sample_type: "Serum" },
  { name: "KOH Preparation", category: "Microbiology", price: 100, sample_type: "Skin/Nail" },
  { name: "L.E. Cell", category: "Hematology", price: 100, sample_type: "Whole Blood" },
  { name: "Lactate", category: "Biochemistry", price: 800, sample_type: "Serum" },
  { name: "LDH (Lactate Dehydrogenase)", category: "Biochemistry", price: 500, sample_type: "Serum" },
  { name: "LDL - Cholesterol", category: "Biochemistry", price: 400, sample_type: "Serum" },
  { name: "LDL : HDL", category: "Biochemistry", price: 100, sample_type: "Serum" },
  { name: "Lead Level", category: "Biochemistry", price: 1500, sample_type: "Whole Blood" },
  { name: "Leishmania / Kala-Azar Antibodies", category: "Serology", price: 1400, sample_type: "Serum" },
  { name: "Leishmania / Kala-Azar Antibody IgG", category: "Serology", price: 500, sample_type: "Serum" },
  { name: "Leishmania / Kala-Azar Antibody IgM", category: "Serology", price: 500, sample_type: "Serum" },
  { name: "Leptospira Antibodies (IgG & IgM)", category: "Serology", price: 1000, sample_type: "Serum" }
];

importBatch(tests).then(() => process.exit());
