const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00005
  { name: "Body Fluid Culture & Sensitivity", category: "Microbiology", price: 200, sample_type: "Body fluid" },
  { name: "Body Fluid for ADA", category: "Biochemistry", price: 600, sample_type: "Body fluid" },
  { name: "Body Fluides for Protein", category: "Biochemistry", price: 100, sample_type: "Body fluid" },
  { name: "Body Fluids (Cell Count, Biochemistry)", category: "Biochemistry", price: 400, sample_type: "Body fluid" },
  { name: "Body Fluids (Cell Type & Cell Count)", category: "Hematology", price: 80, sample_type: "Body fluid" },
  { name: "Body Fluids Biochemistry", category: "Biochemistry", price: 250, sample_type: "Body fluid" },
  { name: "Body Fluids for Chloride", category: "Biochemistry", price: 150, sample_type: "Body fluid" },
  { name: "Body Fluids for Glucose", category: "Biochemistry", price: 50, sample_type: "Body fluid" },
  { name: "Body Fluids for Specific Gravity", category: "Biochemistry", price: 30, sample_type: "Body fluid" },
  { name: "Bone Marrow Aspiration & Cytology", category: "Cytology", price: 600, sample_type: "Bone Marrow" },
  { name: "Bone Marrow Cytology", category: "Cytology", price: 300, sample_type: "Bone Marrow" },
  { name: "Bronchial Brushing for PAP", category: "Cytology", price: 400, sample_type: "Bronchial Brush" },
  { name: "Bronchial Lavage for C/S", category: "Microbiology", price: 200, sample_type: "Bronchial Lavage" },
  { name: "Bronchial Lavage for PAP", category: "Cytology", price: 400, sample_type: "Bronchial Lavage" },
  { name: "Bronchial Washing for C/S", category: "Microbiology", price: 400, sample_type: "Bronchial Washing" },
  { name: "Bronchial Washing for PAP", category: "Cytology", price: 400, sample_type: "Bronchial Washing" },
  { name: "BT & CT (Bleeding Time & Clotting Time)", category: "Hematology", price: 120, sample_type: "Blood" },
  { name: "BT (Bleeding Time)", category: "Hematology", price: 60, sample_type: "Blood" },
  { name: "Buccal Smear for Sex Chromation", category: "Cytology", price: 300, sample_type: "Buccal Smear" },
  { name: "BUN (Blood Urea Nitrogen)", category: "Biochemistry", price: 300, sample_type: "Serum" },
  { name: "C ANCA (Anti-PR3)", category: "Immunology", price: 1000, sample_type: "Serum" },
  { name: "C3 (Complement-3)", category: "Immunology", price: 550, sample_type: "Serum" },
  { name: "C4 (Complement-4)", category: "Immunology", price: 550, sample_type: "Serum" },
  { name: "CA 125 (Ovarian Cancer Marker)", category: "Biochemistry", price: 750, sample_type: "Serum" },
  { name: "CA 15.3 (Breast Cancer Marker)", category: "Biochemistry", price: 600, sample_type: "Serum" },
  { name: "CA 19.9 (Pancreatic Cancer Marker)", category: "Biochemistry", price: 800, sample_type: "Serum" },
  { name: "CA 72.4 (Gastric Cancer Marker)", category: "Biochemistry", price: 1100, sample_type: "Serum" },

  // Image 00006
  { name: "Calcium", category: "Biochemistry", price: 250, sample_type: "Serum" },
  { name: "Calcium (Ionised)", category: "Biochemistry", price: 200, sample_type: "Serum" },
  { name: "Calcium (24 hrs Urine)", category: "Biochemistry", price: 200, sample_type: "24h Urine" },
  { name: "Calsitonin", category: "Biochemistry", price: 1400, sample_type: "Serum" },
  { name: "Capillary Fragility Test", category: "Hematology", price: 150, sample_type: "EDTA Blood" },
  { name: "Carbamazepine", category: "Biochemistry", price: 550, sample_type: "Serum" },
  { name: "Cardiac Enzyme Profile", category: "Biochemistry", price: 850, sample_type: "Serum" },
  { name: "Cardiac Injury Profile", category: "Biochemistry", price: 1750, sample_type: "Serum" },
  { name: "Cardiac Profile", category: "Biochemistry", price: 2270, sample_type: "Serum" },
  { name: "CBC (Complete Blood Count)", category: "Hematology", price: 300, sample_type: "EDTA Blood" },
  { name: "CCT (Creatinine Clearance Test)", category: "Biochemistry", price: 300, sample_type: "Serum & 24h Urine" },
  { name: "CD 3 Lymphocyte", category: "Immunology", price: 1800, sample_type: "EDTA Blood" },
  { name: "CD 4 Lymphocyte", category: "Immunology", price: 1800, sample_type: "EDTA Blood" },
  { name: "CD 8 Lymphocyte", category: "Immunology", price: 1800, sample_type: "EDTA Blood" },
  { name: "CEA (Carcino Embryonic Antigen)", category: "Biochemistry", price: 540, sample_type: "Serum" },
  { name: "Cerebrospinal Fluid (Cell Count & Biochemistry)", category: "Biochemistry", price: 325, sample_type: "CSF" },
  { name: "Cerebrospinal Fluid (Cell Count, Biochemistry, Protein)", category: "Biochemistry", price: 500, sample_type: "CSF" },
  { name: "Cerebrospinal Fluid (Cell Type & Cell Count)", category: "Hematology", price: 200, sample_type: "CSF" },
  { name: "Ceruloplasmin", category: "Biochemistry", price: 600, sample_type: "Serum" },
  { name: "Cervical Smear for PAP Stain", category: "Cytology", price: 700, sample_type: "Cervical Smear" },
  { name: "Cervical Swab AFB Stain", category: "Microbiology", price: 100, sample_type: "Cervical Swab" },
  { name: "Cervical Swab Culture", category: "Microbiology", price: 200, sample_type: "Cervical Swab" },
  { name: "Cervical Swab Gram Stain", category: "Microbiology", price: 100, sample_type: "Cervical Swab" },
  { name: "CFT (Complete Fixation Test)", category: "Serology", price: 800, sample_type: "Serum" },
  { name: "Chikungunya IgG", category: "Serology", price: 600, sample_type: "Serum" }
];

importBatch(tests).then(() => process.exit());
