const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00001
  { name: "Gram Stain Of Urethral Discharge", category: "Microbiology", price: 200, sample_type: "Urethral" },
  { name: "17-OH Progesterone", category: "Biochemistry", price: 1000, sample_type: "Serum" },
  { name: "24 Hrs. Holter Monitoring", category: "Cardiology", price: 1500, sample_type: "Patient" },
  { name: "24 Hrs. Urinary Albumin", category: "Biochemistry", price: 300, sample_type: "24h Urine" },
  { name: "24 Hrs. Urinary Protein", category: "Biochemistry", price: 150, sample_type: "24h Urine" },
  { name: "25-OH Vitamin D (TOTAL)", category: "Biochemistry", price: 1500, sample_type: "Serum" },
  { name: "A G Ratio", category: "Biochemistry", price: 100, sample_type: "Serum" },
  { name: "ABG BLOOD TEST", category: "Biochemistry", price: 1400, sample_type: "Heparin Blood" },
  { name: "Abnormal Cells", category: "Hematology", price: 50, sample_type: "Blood" },
  { name: "Absolute Eosinophils Count", category: "Hematology", price: 150, sample_type: "EDTA Blood" },
  { name: "Absolute Monocytes Count", category: "Hematology", price: 150, sample_type: "EDTA Blood" },
  { name: "Absolute Basophils Count", category: "Hematology", price: 150, sample_type: "EDTA Blood" },
  { name: "Absolute Lymphocytes Count", category: "Hematology", price: 150, sample_type: "EDTA Blood" },
  { name: "Absolute Neutrophils Count", category: "Hematology", price: 150, sample_type: "EDTA Blood" },
  { name: "ACE (Angiotensin Converting Enzyme)", category: "Biochemistry", price: 1400, sample_type: "Serum" },
  { name: "Acid Phosphatase Prostate / PAP", category: "Biochemistry", price: 400, sample_type: "Serum" },
  { name: "Acid Phosphatase Total", category: "Biochemistry", price: 200, sample_type: "Serum" },
  { name: "ACR (Albumin - Creatinine Ratio)", category: "Biochemistry", price: 660, sample_type: "Random Urine" },
  { name: "ACTH (Adrenocorticoprotic Hormone)", category: "Biochemistry", price: 1200, sample_type: "EDTA Plasma" },
  { name: "ADA (Adenosine Deaminase Activity)", category: "Biochemistry", price: 600, sample_type: "Serum/Fluid" },
  { name: "AFB (Z-N Stain)", category: "Microbiology", price: 80, sample_type: "Sputum/Pus" },
  { name: "AFB Culture & Sensitivity", category: "Microbiology", price: 100, sample_type: "Sputum/Pus" },
  { name: "AFB Culture & Sensitivity (Bactec method)", category: "Microbiology", price: 1800, sample_type: "Sputum/Pus" },
  { name: "AFB Culture (Bactec method)", category: "Microbiology", price: 250, sample_type: "Sputum/Pus" },
  { name: "AFB Culture (Conventional Method)", category: "Microbiology", price: 700, sample_type: "Sputum/Pus" },
  { name: "AFP (Alpha Feto Protein)", category: "Biochemistry", price: 400, sample_type: "Serum" },
  { name: "Albert Stain of Smear for KLB", category: "Microbiology", price: 200, sample_type: "Throat Swab" },

  // Image 00002
  { name: "Albumin", category: "Biochemistry", price: 150, sample_type: "Serum" },
  { name: "Alcohol (serum)", category: "Toxicology", price: 900, sample_type: "Serum" },
  { name: "Alcohol (urine)", category: "Toxicology", price: 900, sample_type: "Urine" },
  { name: "Aldehyde Test (AT)", category: "Microbiology", price: 200, sample_type: "Serum" },
  { name: "Aldolase", category: "Biochemistry", price: 400, sample_type: "Serum" },
  { name: "Aldosterone", category: "Biochemistry", price: 1100, sample_type: "Serum" },
  { name: "Allergy (Blood)", category: "Immunology", price: 2100, sample_type: "Serum" },
  { name: "Allergy (Drug)", category: "Immunology", price: 1400, sample_type: "Blood" },
  { name: "Allergy (Modified Skin Prick)", category: "Immunology", price: 600, sample_type: "Skin" },
  { name: "ALP (Alkaline Phosphatase)", category: "Biochemistry", price: 150, sample_type: "Serum" },
  { name: "Alpha Amylase (Serum)", category: "Biochemistry", price: 400, sample_type: "Serum" },
  { name: "Alpha Amylase (Urine)", category: "Biochemistry", price: 80, sample_type: "Urine" },
  { name: "Ammonia", category: "Biochemistry", price: 1400, sample_type: "EDTA Blood" },
  { name: "Amylase", category: "Biochemistry", price: 400, sample_type: "Serum" },
  { name: "Amylase (24 hrs. urine)", category: "Biochemistry", price: 300, sample_type: "24h Urine" },
  { name: "ANA / ANF (Anti Nuclear Antibody) - ELISA", category: "Immunology", price: 660, sample_type: "Serum" },
  { name: "ANA / ANF (Anti Nuclear Antibody) - Semiquantitative", category: "Immunology", price: 400, sample_type: "Serum" },
  { name: "Anaerobic & Aerobic Culture of the...", category: "Microbiology", price: 300, sample_type: "Pus/Swab" },
  { name: "Androgens (Testosterone & DHEA-S)", category: "Biochemistry", price: 500, sample_type: "Serum" },
  { name: "Androsteindione (A4)", category: "Biochemistry", price: 1300, sample_type: "Serum" },
  { name: "Anemia Comprehensive Profile", category: "Hematology", price: 2500, sample_type: "Serum" },
  { name: "Anemia Screening Profile", category: "Hematology", price: 700, sample_type: "Serum" },
  { name: "ANF (Anti Nuclear Factor) Qualitative", category: "Immunology", price: 400, sample_type: "Serum" },
  { name: "ANF (Anti Nuclear Factor) Quantitative", category: "Immunology", price: 400, sample_type: "Serum" }
];

importBatch(tests).then(() => process.exit());
