const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00003
  { name: "Antenatal Profile", category: "Biochemistry", price: 0, sample_type: "Serum" },
  { name: "Anti Cardiolipin Antibody IgA", category: "Immunology", price: 400, sample_type: "Serum" },
  { name: "Anti Cardiolipin Antibody IgA & IgG", category: "Immunology", price: 12000, sample_type: "Serum" },
  { name: "Anti Cardiolipin Antibody IgA & IgM", category: "Immunology", price: 1000, sample_type: "Serum" },
  { name: "Anti Cardiolipin Antibody IgA, IgG & IgM", category: "Immunology", price: 1500, sample_type: "Serum" },
  { name: "Anti Cardiolipin Antibody IgG", category: "Immunology", price: 600, sample_type: "Serum" },
  { name: "Anti Cardiolipin Antibody IgG & IgM", category: "Immunology", price: 1000, sample_type: "Serum" },
  { name: "Anti Cardiolipin Antibody IgM", category: "Immunology", price: 600, sample_type: "Serum" },
  { name: "Anti CCP (Cyclic Citrullinated Peptide)", category: "Immunology", price: 1080, sample_type: "Serum" },
  { name: "Anti CCPAB", category: "Immunology", price: 800, sample_type: "Serum" },
  { name: "Anti ds DNA Antibody", category: "Immunology", price: 500, sample_type: "Serum" },
  { name: "Anti HAV (Hepatitis A Virus)", category: "Microbiology", price: 400, sample_type: "Serum" },
  { name: "Anti HCV Antibody", category: "Microbiology", price: 600, sample_type: "Serum" },
  { name: "Anti Insulin Antibody", category: "Immunology", price: 900, sample_type: "Serum" },
  { name: "Anti Leptospira Antibody", category: "Microbiology", price: 2000, sample_type: "Serum" },
  { name: "Anti LKM", category: "Immunology", price: 1200, sample_type: "Serum" },
  { name: "Anti Microsomal Antibody", category: "Immunology", price: 500, sample_type: "Serum" },
  { name: "Anti Sperm Antibody", category: "Immunology", price: 500, sample_type: "Serum" },
  { name: "Anti ss DNA Antibody", category: "Immunology", price: 700, sample_type: "Serum" },
  { name: "Anti Tg (Anti Thyroglobulin)", category: "Immunology", price: 500, sample_type: "Serum" },
  { name: "Anti TPO (Anti Thyroid Peroxidase)", category: "Immunology", price: 900, sample_type: "Serum" },
  { name: "Any Fluid for PAP", category: "Cytology", price: 400, sample_type: "Fluid" },
  { name: "Apolipo Protein B", category: "Biochemistry", price: 500, sample_type: "Serum" },
  { name: "Apolipoprotein A1", category: "Biochemistry", price: 500, sample_type: "Serum" },
  { name: "APTT (Activated Partial Thromboplastin Time)", category: "Hematology", price: 500, sample_type: "Citrate Plasma" },

  // Image 00004
  { name: "Arsenic (Serum)", category: "Toxicology", price: 1500, sample_type: "Serum" },
  { name: "Arsenic (Urine)", category: "Toxicology", price: 1500, sample_type: "24h Urine" },
  { name: "Ascitic Fluid (Cell Count, Biochemistry)", category: "Biochemistry", price: 800, sample_type: "Ascitic Fluid" },
  { name: "Ascitic Fluid for ADA", category: "Biochemistry", price: 600, sample_type: "Ascitic Fluid" },
  { name: "Ascitic Fluid for Protein", category: "Biochemistry", price: 200, sample_type: "Ascitic Fluid" },
  { name: "Ascitic Fluids (Cell Type & Cell Count)", category: "Hematology", price: 300, sample_type: "Ascitic Fluid" },
  { name: "Ascitic Fluids Gram Stain", category: "Microbiology", price: 150, sample_type: "Ascitic Fluid" },
  { name: "ASO (Anti Streptolysin-O) Test", category: "Serology", price: 400, sample_type: "Serum" },
  { name: "Aspirated Fluid (Cell Type, Cell Count)", category: "Hematology", price: 500, sample_type: "Aspirated Fluid" },
  { name: "Autoimmune Profile", category: "Immunology", price: 1200, sample_type: "Serum" },
  { name: "BACCAL Smear for BRR Body", category: "Cytology", price: 150, sample_type: "Smear" },
  { name: "Bactec Culture & Sensitivity for Aerobic", category: "Microbiology", price: 700, sample_type: "Blood" },
  { name: "Bactec Culture & Sensitivity for Anaerobic", category: "Microbiology", price: 500, sample_type: "Blood" },
  { name: "Bactec Culture for Aerobic Bacteria", category: "Microbiology", price: 500, sample_type: "Blood" },
  { name: "Bactec Culture for Anaerobic Bacteria", category: "Microbiology", price: 500, sample_type: "Blood" },
  { name: "Beta-2 Microglobulin", category: "Biochemistry", price: 1600, sample_type: "Serum" },
  { name: "Beta hCG (Beta human Chorionic Gonadotropin)", category: "Biochemistry", price: 600, sample_type: "Serum" },
  { name: "Bicarbonate (HCO3)", category: "Biochemistry", price: 200, sample_type: "Serum" },
  { name: "Bilirubin Total", category: "Biochemistry", price: 80, sample_type: "Serum" },
  { name: "Bilirubin Total, Direct & Indirect", category: "Biochemistry", price: 150, sample_type: "Serum" },
  { name: "Biopsy (Medium Section)", category: "Histopathology", price: 1250, sample_type: "Tissue" },
  { name: "Biopsy (Small Section)", category: "Histopathology", price: 800, sample_type: "Tissue" },
  { name: "Blood Culture & Sensitivity", category: "Microbiology", price: 500, sample_type: "Blood" },
  { name: "Blood Culture & Sensitivity (Conventional)", category: "Microbiology", price: 250, sample_type: "Blood" },
  { name: "Blood Culture (Conventional Method)", category: "Microbiology", price: 200, sample_type: "Blood" },
  { name: "Blood Culture (Rapid Bactec method)", category: "Microbiology", price: 600, sample_type: "Blood" },
  { name: "Blood Group ABO & Rh (D) factor", category: "Hematology", price: 50, sample_type: "Blood" }
];

importBatch(tests).then(() => process.exit());
