const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00015
  { name: "Digital XRAY Foot AP / Lat / Obl", category: "X-Ray", price: 350, sample_type: "Imaging" },
  { name: "Digital XRAY Foot AP / Obl", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Foot Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Foot Obl", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Foot Trans Lat (In Wt. Bearing)", category: "X-Ray", price: 125, sample_type: "Imaging" },
  { name: "Digital XRAY Fore Arm AP", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Fore Arm AP / Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Fore Arm Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Frontal/Sinus", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Hand AP / Lat / Obl", category: "X-Ray", price: 350, sample_type: "Imaging" },
  { name: "Digital XRAY Hand AP / Lat - Rt / Lt", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Heel (Both) AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Heel (Left/Right) AP", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Heel (Left/Right) AP / Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Heel (Left/Right) Axial", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Heel (Left/Right) Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Hip (Both) AP", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Hip (Both) AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Hip (Both) Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Hip (Left/Right) AP", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Hip (Left/Right) AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Hip (Left/Right) Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY HSG (Dye Extra)", category: "X-Ray", price: 1500, sample_type: "Imaging" },
  { name: "Digital XRAY HSG (Hysterosalpingogram)", category: "X-Ray", price: 1500, sample_type: "Imaging" },
  { name: "Digital XRAY HSG with Contrast", category: "X-Ray", price: 1000, sample_type: "Imaging" },
  { name: "Digital XRAY Humerus AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },

  // Image 00016
  { name: "Digital XRAY I.O. Dental", category: "X-Ray", price: 200, sample_type: "Imaging" },
  { name: "Digital XRAY I.O. Dental 2", category: "X-Ray", price: 400, sample_type: "Imaging" },
  { name: "Digital XRAY I.O. Dental 3", category: "X-Ray", price: 450, sample_type: "Imaging" },
  { name: "Digital XRAY I.O. Dental 4", category: "X-Ray", price: 600, sample_type: "Imaging" },
  { name: "Digital XRAY Intra-Oditory Canal", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digital XRAY Intravenous Pyelogram", category: "X-Ray", price: 2000, sample_type: "Imaging" },
  { name: "Digital XRAY Intravenous Urography", category: "X-Ray", price: 2000, sample_type: "Imaging" },
  { name: "Digital XRAY IOPA", category: "X-Ray", price: 200, sample_type: "Imaging" },
  { name: "Digital XRAY IVP with Dye / Contrast", category: "X-Ray", price: 3000, sample_type: "Imaging" },
  { name: "Digital XRAY IVP with MCU (2 Plates)", category: "X-Ray", price: 1100, sample_type: "Imaging" },
  { name: "Digital XRAY IVP with Non Ionic Contrast", category: "X-Ray", price: 1800, sample_type: "Imaging" },
  { name: "Digital XRAY Kidney (Both)", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Kidney (Left/Right)", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Knee (Both) AP", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Knee (Both) AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Knee (Both) AP / Lat / Skyline", category: "X-Ray", price: 700, sample_type: "Imaging" },
  { name: "Digital XRAY Knee (Both) AP / Skyline", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Knee (Both) Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Knee (Both) Lat / Skyline", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Knee (Both) Skyline", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Knee (Left/Right) AP", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Knee (Left/Right) AP / Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Knee (Left/Right) Inter-Condylar", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digital XRAY Knee (Left/Right) Lat", category: "X-Ray", price: 250, sample_type: "Imaging" }
];

importBatch(tests).then(() => process.exit());
