const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00031
  { name: "MRI FACE AND NECK", category: "MRI", price: 8000, sample_type: "N/A" },
  { name: "MRI FISTULOGRAM/PERINEUM", category: "MRI", price: 6500, sample_type: "N/A" },
  { name: "MRI FOOT/LEG/FEMUR & HAND/FOREARM", category: "MRI", price: 6000, sample_type: "N/A" },
  { name: "MRI L. S. SPINE WITH S. I. JOINT", category: "MRI", price: 9000, sample_type: "N/A" },
  { name: "MRI MRCP,PELVIS,LOWER & UPPER ABDOMEN", category: "MRI", price: 6000, sample_type: "N/A" },
  { name: "MRI NECK", category: "MRI", price: 6000, sample_type: "N/A" },
  { name: "MRI NECK WITH ANGIO", category: "MRI", price: 7000, sample_type: "N/A" },
  { name: "MRI OF LEFT/RIGHT KNEE JOINT", category: "MRI", price: 6000, sample_type: "N/A" },
  { name: "MRI ORBIT (BOTH)", category: "MRI", price: 6000, sample_type: "N/A" },
  { name: "MRI PELVIS WITH BOTH HIP", category: "MRI", price: 7000, sample_type: "N/A" },
  { name: "MRI SCREENING(ANY SINGLE PART)", category: "MRI", price: 3000, sample_type: "N/A" },
  { name: "MRI SPINE(C. SPINE/L.S. SPINE/D. L. SPINE)", category: "MRI", price: 6000, sample_type: "N/A" },
  { name: "MRI TM JOINT", category: "MRI", price: 6000, sample_type: "N/A" },
  { name: "MRI TM JOINT, ORBIT, PITUITARY", category: "MRI", price: 6000, sample_type: "N/A" },
  { name: "MRI WHOLE ABDOMEN", category: "MRI", price: 8000, sample_type: "N/A" },
  { name: "MRI WHOLE SPINE", category: "MRI", price: 12000, sample_type: "N/A" },
  { name: "MRI WRIST/ELBOW/SHOULDER (RT/LT)", category: "MRI", price: 6000, sample_type: "N/A" },
  { name: "Nasal Swab AFB Stain", category: "Microbiology", price: 150, sample_type: "Nasal Swab" },
  { name: "Nasal Swab eosinophil", category: "Hematology", price: 100, sample_type: "Nasal Swab" },
  { name: "Nasal Swab for Eosinophil Count", category: "Hematology", price: 120, sample_type: "Nasal Swab" },
  { name: "Nasal Swab for KLB", category: "Microbiology", price: 150, sample_type: "Nasal Swab" },
  { name: "Nasal Swab Gram Stain", category: "Microbiology", price: 150, sample_type: "Nasal Swab" },
  { name: "NCV", category: "Neurology", price: 2000, sample_type: "N/A" },
  { name: "NCV 4 LIMBS", category: "Neurology", price: 2800, sample_type: "N/A" },
  { name: "NCV LOWER LIMBS", category: "Neurology", price: 1800, sample_type: "N/A" },
  { name: "NCV LOWER LIMBS WITH FEMORAL", category: "Neurology", price: 1400, sample_type: "N/A" },
  { name: "NCV UPPER LIMBS", category: "Neurology", price: 1800, sample_type: "N/A" },

  // Image 00032
  { name: "NCV UPPER LIMBS WITH BRACHIAL", category: "Neurology", price: 1400, sample_type: "N/A" },
  { name: "NPN (Non Protein Nitrogen)", category: "Biochemistry", price: 70, sample_type: "Serum" },
  { name: "Oncology Profile", category: "Profile", price: 1450, sample_type: "Serum" },
  { name: "Optimal IT Antigen", category: "Serology", price: 450, sample_type: "Serum" },
  { name: "Osmotic fragility Test", category: "Hematology", price: 150, sample_type: "Whole Blood" },
  { name: "Ovarian Cancer Monitor Profile", category: "Profile", price: 900, sample_type: "Serum" },
  { name: "Ovarian Function Profile", category: "Profile", price: 1500, sample_type: "Serum" },
  { name: "Oxygen for each Day(after 1st 3 Days)", category: "Other", price: 50, sample_type: "N/A" },
  { name: "Oxygen( 3 Days)", category: "Other", price: 500, sample_type: "N/A" },
  { name: "P ANCA (Anti - PR3)", category: "Serology", price: 1200, sample_type: "Serum" },
  { name: "Pancreatic Cancer Monitor Profile", category: "Profile", price: 900, sample_type: "Serum" },
  { name: "P-anti Neutrophil Cytoplasmic Antibody", category: "Serology", price: 1000, sample_type: "Serum" },
  { name: "PAP Smear", category: "Cytology", price: 1000, sample_type: "Smear" },
  { name: "Parietal Cell Antibody", category: "Serology", price: 1500, sample_type: "Serum" },
  { name: "PBI", category: "Biochemistry", price: 300, sample_type: "Serum" },
  { name: "PCV (Packed Cell Volume)", category: "Hematology", price: 200, sample_type: "Whole Blood" },
  { name: "Pericardial Fluid for AFB Stain", category: "Microbiology", price: 100, sample_type: "Pericardial Fluid" },
  { name: "Pericardial Fluid for Cell Count & Differential", category: "Hematology", price: 100, sample_type: "Pericardial Fluid" },
  { name: "Pericardial Fluid for Chloride", category: "Biochemistry", price: 150, sample_type: "Pericardial Fluid" },
  { name: "Pericardial Fluid for Gram Stain", category: "Microbiology", price: 80, sample_type: "Pericardial Fluid" },
  { name: "Pericardial Fluid for Protein", category: "Biochemistry", price: 150, sample_type: "Pericardial Fluid" },
  { name: "Pericardial Fluid for Specific Gravity", category: "Biochemistry", price: 80, sample_type: "Pericardial Fluid" },
  { name: "Pericardial Fluid for Sugar", category: "Biochemistry", price: 50, sample_type: "Pericardial Fluid" },
  { name: "Peripheral Smear", category: "Hematology", price: 100, sample_type: "Whole Blood" },
  { name: "Peritonial Fluid Amylase", category: "Biochemistry", price: 250, sample_type: "Peritonial Fluid" },
  { name: "Peritonial Fluid Chloride", category: "Biochemistry", price: 100, sample_type: "Peritonial Fluid" }
];

importBatch(tests).then(() => process.exit());
