const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00021
  { name: "Digital XRAY Thigh AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Thigh Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Throacic AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Throat AP / Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Tibia-Fibula AP", category: "X-Ray", price: 200, sample_type: "Imaging" },
  { name: "Digital XRAY Tibia-Fibula AP / Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Tibia-Fibula Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY TM Joint", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY TM Joint (Ipsilateral - Open/Close)", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY T-Tube Cholecystogram", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY T-tube Clolangiogram", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Under Fluroscopy", category: "X-Ray", price: 100, sample_type: "Imaging" },
  { name: "Digital XRAY Urethrogram", category: "X-Ray", price: 1500, sample_type: "Imaging" },
  { name: "Digital XRAY Urethrogram (Ascending)", category: "X-Ray", price: 1500, sample_type: "Imaging" },
  { name: "Digital XRAY Urethrogram (Cysto)", category: "X-Ray", price: 1500, sample_type: "Imaging" },
  { name: "Digital XRAY Urethrogram (Retrograde)", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Venography", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Whole Spine AP / Lat", category: "X-Ray", price: 1200, sample_type: "Imaging" },
  { name: "Digital XRAY Wrist AP", category: "X-Ray", price: 200, sample_type: "Imaging" },
  { name: "Digital XRAY Wrist AP / Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Wrist AP / Lat / Obl", category: "X-Ray", price: 350, sample_type: "Imaging" },
  { name: "Digital XRAY Wrist AP / Lat / Scaphoid", category: "X-Ray", price: 350, sample_type: "Imaging" },
  { name: "Digital XRAY Wrist Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Wrist Scaphoid", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digoxin", category: "Biochemistry", price: 700, sample_type: "Serum" },
  { name: "DLC (Differential Leukocytes Count)", category: "Hematology", price: 50, sample_type: "Whole Blood" },
  { name: "Ear Swab AFB Stain", category: "Microbiology", price: 150, sample_type: "Ear Swab" },
  { name: "Ear Swab Gram Stain", category: "Microbiology", price: 100, sample_type: "Ear Swab" },

  // Image 00022
  { name: "ECG", category: "Cardiology", price: 200, sample_type: "N/A" },
  { name: "Echo Cardiography", category: "Cardiology", price: 1600, sample_type: "N/A" },
  { name: "Echo Cardiography Doppler Study", category: "Cardiology", price: 1300, sample_type: "N/A" },
  { name: "Ectocervical Swab Culture", category: "Microbiology", price: 200, sample_type: "Swab" },
  { name: "EEG", category: "Neurology", price: 1200, sample_type: "N/A" },
  { name: "Electrolyte Profile", category: "Biochemistry", price: 500, sample_type: "Serum" },
  { name: "EMG & NCV FOUR LIMBS", category: "Neurology", price: 4600, sample_type: "N/A" },
  { name: "EMG & NCV FOUR LIMBS(NEEDLE)", category: "Neurology", price: 3800, sample_type: "N/A" },
  { name: "EMG & NCV LOWER LIMBS", category: "Neurology", price: 2200, sample_type: "N/A" },
  { name: "EMG & NCV LOWER LIMBS(NEEDLE)", category: "Neurology", price: 2400, sample_type: "N/A" },
  { name: "EMG & NCV RIGHT LOWER LIMBS", category: "Neurology", price: 2400, sample_type: "N/A" },
  { name: "EMG & NCV UPPER LIMBS", category: "Neurology", price: 2200, sample_type: "N/A" },
  { name: "EMG & NCV UPPER LIMBS (NEEDLE)", category: "Neurology", price: 2400, sample_type: "N/A" },
  { name: "Endocervical Swab Culture", category: "Microbiology", price: 200, sample_type: "Swab" },
  { name: "ENTROCHECK CARD TEST - IgM & IgG", category: "Serology", price: 400, sample_type: "Serum" },
  { name: "ESR (Erythrocyte Sedimentation Rate)", category: "Hematology", price: 80, sample_type: "Whole Blood" },
  { name: "Esterified Cholesterol", category: "Biochemistry", price: 100, sample_type: "Serum" },
  { name: "Estriol (E3)", category: "Hormone", price: 800, sample_type: "Serum" },
  { name: "Estrogen / Estradiol (E2)", category: "Hormone", price: 450, sample_type: "Serum" },
  { name: "EXECUTIVE HEALTH CHECK-UP", category: "Profile", price: 3870, sample_type: "Various" },
  { name: "Eye Swab AFB Stain", category: "Microbiology", price: 150, sample_type: "Eye Swab" },
  { name: "Eye Swab Gram Stain", category: "Microbiology", price: 150, sample_type: "Eye Swab" },
  { name: "Factor IX Deficient", category: "Hematology", price: 2000, sample_type: "Plasma" }
];

importBatch(tests).then(() => process.exit());
