const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00037
  { name: "Sputum AFB Stain (3 consecutive Days)", category: "Microbiology", price: 100, sample_type: "Sputum" },
  { name: "Sputum Culture (Non AFB)", category: "Microbiology", price: 150, sample_type: "Sputum" },
  { name: "Sputum Culture & Sensitivity", category: "Microbiology", price: 300, sample_type: "Sputum" },
  { name: "Sputum Gram Stain", category: "Microbiology", price: 200, sample_type: "Sputum" },
  { name: "Sputum Leishman Stain (3 consecutive)", category: "Microbiology", price: 200, sample_type: "Sputum" },
  { name: "Sputum RE (Leishman Stain + Gram)", category: "Microbiology", price: 150, sample_type: "Sputum" },
  { name: "STD (Sexually Transmitted Disease) Profile", category: "Profile", price: 900, sample_type: "Multiple" },
  { name: "Stone Analysis (Urinary / Gall Bladder)", category: "Biochemistry", price: 500, sample_type: "Stone" },
  { name: "Stool Concentration Method", category: "Microbiology", price: 300, sample_type: "Stool" },
  { name: "Stool Culture", category: "Microbiology", price: 100, sample_type: "Stool" },
  { name: "Stool Culture & Sensitivity", category: "Microbiology", price: 300, sample_type: "Stool" },
  { name: "Stool OBT", category: "Microbiology", price: 100, sample_type: "Stool" },
  { name: "Stool OBT + RE (3 Days)", category: "Microbiology", price: 600, sample_type: "Stool" },
  { name: "Stool OPC", category: "Microbiology", price: 150, sample_type: "Stool" },
  { name: "Stool pH", category: "Microbiology", price: 100, sample_type: "Stool" },
  { name: "Stool RE (3 Consecutive Days)", category: "Microbiology", price: 450, sample_type: "Stool" },
  { name: "Stool RE (Routine Examination)", category: "Microbiology", price: 150, sample_type: "Stool" },
  { name: "Stool RE + Red Sub + pH", category: "Microbiology", price: 200, sample_type: "Stool" },
  { name: "Stool Reducing substance", category: "Microbiology", price: 70, sample_type: "Stool" },
  { name: "Swab Culture & Sensitivity for any site", category: "Microbiology", price: 100, sample_type: "Swab" },
  { name: "Swab for Trichomona (Vaginal & Cervical)", category: "Microbiology", price: 150, sample_type: "Swab" },
  { name: "Synovial Fluid for AFB Stain", category: "Microbiology", price: 80, sample_type: "Synovial Fluid" },
  { name: "Synovial Fluid for Calcium", category: "Biochemistry", price: 100, sample_type: "Synovial Fluid" },
  { name: "Synovial Fluid for Crystals", category: "Other", price: 90, sample_type: "Synovial Fluid" },
  { name: "Synovial Fluid for Uric Acid", category: "Biochemistry", price: 70, sample_type: "Synovial Fluid" },

  // Image 00038
  { name: "T3 & TSH", category: "Hormone", price: 500, sample_type: "Serum" },
  { name: "T3 & US-TSH", category: "Hormone", price: 500, sample_type: "Serum" },
  { name: "T3 (Total Tri-iodothyronine)", category: "Hormone", price: 300, sample_type: "Serum" },
  { name: "T3, T4 & TSH", category: "Hormone", price: 600, sample_type: "Serum" },
  { name: "T4 & US-TSH", category: "Hormone", price: 500, sample_type: "Serum" },
  { name: "T4 & TSH", category: "Hormone", price: 300, sample_type: "Serum" },
  { name: "T4 (Total Thyroxine)", category: "Hormone", price: 1400, sample_type: "Serum" },
  { name: "Taenia Echinococcus", category: "Serology", price: 1200, sample_type: "Serum" },
  { name: "TB DNA PCR", category: "Other", price: 1500, sample_type: "Multiple" },
  { name: "TB GOLD", category: "Serology", price: 500, sample_type: "Serum" },
  { name: "TB IgA", category: "Serology", price: 1000, sample_type: "Serum" },
  { name: "TB IgA & IgG", category: "Serology", price: 700, sample_type: "Serum" },
  { name: "TB IgA & IgM", category: "Serology", price: 1050, sample_type: "Serum" },
  { name: "TB IgA, IgG & IgM", category: "Serology", price: 500, sample_type: "Serum" },
  { name: "TB IgG", category: "Serology", price: 350, sample_type: "Serum" },
  { name: "TB IgG & IgM", category: "Serology", price: 500, sample_type: "Serum" },
  { name: "TB IgM", category: "Serology", price: 600, sample_type: "Serum" },
  { name: "TBG (Thyroxine Binding Globulin)", category: "Hormone", price: 800, sample_type: "Serum" },
  { name: "TC & DC", category: "Hematology", price: 150, sample_type: "Whole Blood" },
  { name: "TC, DC & ESR", category: "Hematology", price: 260, sample_type: "Whole Blood" },
  { name: "TC, DC & MP", category: "Hematology", price: 800, sample_type: "Whole Blood" },
  { name: "Testicular Cancer Monitor Profile", category: "Profile", price: 1000, sample_type: "Serum" },
  { name: "Testicular Function Profile", category: "Profile", price: 450, sample_type: "Serum" },
  { name: "Testosterone", category: "Hormone", price: 1650, sample_type: "Serum" },
  { name: "Testosterone + Estradiol + Progesterone", category: "Profile", price: 1500, sample_type: "Serum" },
  { name: "Thalassemia Profile", category: "Profile", price: 2500, sample_type: "Whole Blood" }
];

importBatch(tests).then(() => process.exit());
