const { importBatch } = require('./import_helper.js');

const tests = [
  // Image 00019
  { name: "Digital XRAY Palm AP", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Palm AP / Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Palm Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Pelvis (Frog Leg)", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Pelvis (Prone)", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Pelvis AP", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Pelvis AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Pelvis Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Per Plate", category: "X-Ray", price: 125, sample_type: "Imaging" },
  { name: "Digital XRAY PNS Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY PNS OM", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Portable", category: "X-Ray", price: 1000, sample_type: "Imaging" },
  { name: "Digital XRAY Ribs AP", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digital XRAY Ribs AP / Lat", category: "X-Ray", price: 300, sample_type: "Imaging" },
  { name: "Digital XRAY Ribs AP / Obl", category: "X-Ray", price: 300, sample_type: "Imaging" },
  { name: "Digital XRAY Ribs Lat", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digital XRAY Ribs Obl", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digital XRAY S I Joint OBL", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Sacrum & Coccyx AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Sacrum AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Sacrum Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Sacrum PA", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Scapula AP", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Shoulder AP", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Shoulder AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Shoulder AP / Lat / Axial", category: "X-Ray", price: 750, sample_type: "Imaging" },
  { name: "Digital XRAY Shoulder Axial", category: "X-Ray", price: 200, sample_type: "Imaging" },

  // Image 00020
  { name: "Digital XRAY Shoulder Bird's Eye", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digital XRAY Shoulder Lat", category: "X-Ray", price: 200, sample_type: "Imaging" },
  { name: "Digital XRAY Sialogram", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Sinugram", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Skull AP", category: "X-Ray", price: 200, sample_type: "Imaging" },
  { name: "Digital XRAY Skull AP / Lat", category: "X-Ray", price: 400, sample_type: "Imaging" },
  { name: "Digital XRAY Skull Axial", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digital XRAY Skull-Base", category: "X-Ray", price: 200, sample_type: "Imaging" },
  { name: "Digital XRAY Skull for Sella", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digital XRAY Skull Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Skull PA", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Skull Towne's", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digital XRAY Soft Tissue Nasopharynx", category: "X-Ray", price: 200, sample_type: "Imaging" },
  { name: "Digital XRAY Soft Tissue Neck AP", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Soft Tissue Neck AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Soft Tissue Neck Lat", category: "X-Ray", price: 250, sample_type: "Imaging" },
  { name: "Digital XRAY Sternoclavicular Joint", category: "X-Ray", price: 125, sample_type: "Imaging" },
  { name: "Digital XRAY Sternum AP", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digital XRAY Sternum AP / Lat", category: "X-Ray", price: 300, sample_type: "Imaging" },
  { name: "Digital XRAY Sternum Lat", category: "X-Ray", price: 150, sample_type: "Imaging" },
  { name: "Digital XRAY Styloid Process", category: "X-Ray", price: 200, sample_type: "Imaging" },
  { name: "Digital XRAY Sub Mandibular AP / Lat", category: "X-Ray", price: 400, sample_type: "Imaging" },
  { name: "Digital XRAY Sub-Mandibular Lat", category: "X-Ray", price: 200, sample_type: "Imaging" },
  { name: "Digital XRAY Thigh AP", category: "X-Ray", price: 200, sample_type: "Imaging" },
  { name: "Digital XRAY Thigh AP / Lat", category: "X-Ray", price: 500, sample_type: "Imaging" },
  { name: "Digital XRAY Thigh Lat", category: "X-Ray", price: 250, sample_type: "Imaging" }
];

importBatch(tests).then(() => process.exit());
