const PATHOLOGY_REPORT_CATALOG = [
  // Haematology
  { name: "Mean Platelet Volume (MPV)", code: "PF001", category: "Hematology", sampleType: "Whole Blood", turnaroundHours: 8 },
  { name: "Platelet Distribution Width (PDW)", code: "PF002", category: "Hematology", sampleType: "Whole Blood", turnaroundHours: 8 },
  { name: "Factor XII Deficiency", code: "PF003", category: "Hematology", sampleType: "Citrated Plasma", turnaroundHours: 24 },
  { name: "Factor XIII Deficiency", code: "PF004", category: "Hematology", sampleType: "Citrated Plasma", turnaroundHours: 24 },
  { name: "Factor XI Deficiency", code: "PF005", category: "Hematology", sampleType: "Citrated Plasma", turnaroundHours: 24 },
  { name: "Factor X Deficiency", code: "PF006", category: "Hematology", sampleType: "Citrated Plasma", turnaroundHours: 24 },
  { name: "Immature Platelet Fraction (IPF)", code: "PF007", category: "Hematology", sampleType: "Whole Blood", turnaroundHours: 8 },
  { name: "Factor VIII (Antihemophilic Factor A)", code: "PF065", category: "Hematology", sampleType: "Plasma", turnaroundHours: 8 },

  // Molecular genetics
  { name: "RT-PCR", code: "PF008", category: "Molecular", sampleType: "Nasopharyngeal / Oropharyngeal Swab", turnaroundHours: 24 },
  { name: "Cystic Fibrosis (CF) Gene Mutation", code: "PF009", category: "Genetics", sampleType: "Whole Blood", turnaroundHours: 72 },
  { name: "Thiopurine Methyltransferase (TPMT)", code: "PF010", category: "Genetics", sampleType: "Whole Blood", turnaroundHours: 72 },
  { name: "Factor II Mutation", code: "PF011", category: "Genetics", sampleType: "Whole Blood", turnaroundHours: 72 },
  { name: "Cystic Fibrosis (CF), Newborn, Screen", code: "PF066", category: "Newborn Screening", sampleType: "Blood", turnaroundHours: 168 },
  { name: "Factor II", code: "PF067", category: "Hematology", sampleType: "Plasma", turnaroundHours: 8 },
  { name: "Karyotype", code: "PF068", category: "Genetics", sampleType: "Blood", turnaroundHours: 168 },

  // Biochemistry
  { name: "Vitamin C", code: "PF012", category: "Biochemistry", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Vitamin K", code: "PF013", category: "Biochemistry", sampleType: "Plasma", turnaroundHours: 24 },
  { name: "Vitamin E", code: "PF014", category: "Biochemistry", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Indirect Bilirubin", code: "PF015", category: "Biochemistry", sampleType: "Serum", turnaroundHours: 8 },
  { name: "Comprehensive Metabolic Panel (CMP)", code: "PF016", category: "Biochemistry", sampleType: "Serum", turnaroundHours: 12 },
  { name: "Beta-Hydroxybutyrate", code: "PF017", category: "Biochemistry", sampleType: "Serum", turnaroundHours: 12 },
  { name: "Flecainide", code: "PF018", category: "Biochemistry", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Serum Osmolality", code: "PF019", category: "Biochemistry", sampleType: "Serum", turnaroundHours: 12 },
  { name: "Selenium", code: "PF020", category: "Biochemistry", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Manganese", code: "PF021", category: "Biochemistry", sampleType: "Whole Blood", turnaroundHours: 24 },
  { name: "B-Type Natriuretic Peptide (BNP)", code: "PF022", category: "Biochemistry", sampleType: "Plasma", turnaroundHours: 12 },
  { name: "Creatine Kinase (Total CK)", code: "PF023", category: "Biochemistry", sampleType: "Serum", turnaroundHours: 12 },
  { name: "Haptoglobin", code: "PF024", category: "Biochemistry", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Tacrolimus", code: "PF025", category: "Biochemistry", sampleType: "Whole Blood", turnaroundHours: 24 },

  // Microbiology and tumour markers
  { name: "Group B Streptococcus (GBS)", code: "PF026", category: "Microbiology", sampleType: "Vaginal / Rectal Swab", turnaroundHours: 48 },
  { name: "Ova and Parasite Examination", code: "PF027", category: "Microbiology", sampleType: "Stool", turnaroundHours: 24 },
  { name: "Mycobacterial Panel", code: "PF028", category: "Microbiology", sampleType: "Sputum / Specimen", turnaroundHours: 72 },
  { name: "Clostridioides difficile Toxin", code: "PF029", category: "Microbiology", sampleType: "Stool", turnaroundHours: 24 },
  { name: "Respiratory Syncytial Virus (RSV)", code: "PF030", category: "Microbiology", sampleType: "Nasopharyngeal Swab", turnaroundHours: 24 },
  { name: "Pertussis", code: "PF031", category: "Microbiology", sampleType: "Nasopharyngeal Swab", turnaroundHours: 24 },
  { name: "Gonorrhea", code: "PF032", category: "Microbiology", sampleType: "Swab / Urine", turnaroundHours: 24 },
  { name: "Des-gamma-carboxy Prothrombin (DCP)", code: "PF033", category: "Tumor Markers", sampleType: "Serum", turnaroundHours: 24 },
  { name: "HER2", code: "PF034", category: "Tumor Markers", sampleType: "Tissue", turnaroundHours: 72 },
  { name: "Galectin-3", code: "PF035", category: "Tumor Markers", sampleType: "Serum", turnaroundHours: 24 },
  { name: "PAX8", code: "PF036", category: "Tumor Markers", sampleType: "Tissue", turnaroundHours: 72 },
  { name: "Double Marker", code: "PF037", category: "Tumor Markers", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Triple Marker", code: "PF038", category: "Tumor Markers", sampleType: "Serum", turnaroundHours: 24 },

  // Immunology
  { name: "HBsAg Quantitative", code: "PF039", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Anti-A Titre", code: "PF040", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Anti-B Titre", code: "PF041", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Anti-Ribosomal P Antibody", code: "PF042", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Anti-Histone Antibody", code: "PF043", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "GQ1b Antibody IgG", code: "PF044", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "GM1 Antibody IgM", code: "PF045", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "GM1 Antibody IgG", code: "PF046", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "GD1b Antibody IgG", code: "PF047", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "GD1a Antibody IgM", code: "PF048", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "GD1a Antibody IgG", code: "PF049", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Soluble Liver Antigen (SLA) Antibody", code: "PF050", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "GAD65 Antibody", code: "PF051", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Arthritis Profile", code: "PF052", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "High-Sensitivity C-Reactive Protein (hs-CRP)", code: "PF053", category: "Immunology", sampleType: "Serum", turnaroundHours: 12 },
  { name: "Beta-2 Glycoprotein I (B2GPI) Antibody", code: "PF054", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Toxoplasma Antibodies Panel", code: "TOXO001", category: "Immunology", sampleType: "Serum", turnaroundHours: 1 },
  { name: "Rheumatoid Factor, RA", code: "RF001", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Antistreptolysin O, ASO Titer", code: "ASO001", category: "Immunology", sampleType: "Serum", turnaroundHours: 24 },

  // Clinical pathology, histopathology, endocrinology and toxicology
  { name: "Semen Analysis - Seminogram", code: "SEMEN001", category: "Clinical Pathology", sampleType: "Semen", turnaroundHours: 1 },
  { name: "Porphyrins", code: "PORPHY001", category: "Biochemistry", sampleType: "Blood (3 ml)", turnaroundHours: 4 },
  { name: "Occult Blood Stool Examination", code: "OCCULT001", category: "Clinical Pathology", sampleType: "Stool", turnaroundHours: 24 },
  { name: "Cerebrospinal Fluid (CSF) Analysis", code: "CSF001", category: "Clinical Pathology", sampleType: "CSF", turnaroundHours: 4 },
  { name: "Thyroid Stimulating Hormone (TSH)", code: "TSH001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Thyroid Profile", code: "THYPRO001", category: "Endocrinology", sampleType: "Serum (2 ml)", turnaroundHours: 24 },
  { name: "Triiodothyronine (T3), Total", code: "T3TOTAL001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Testosterone, Total", code: "TESTO001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Progesterone", code: "PROG001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Cortisone", code: "CORTISONE001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "HCG, Beta, Total, Pregnancy", code: "BETAHCG001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Prolactin (PRL)", code: "PRL001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Dehydroepiandrosterone (DHEA)", code: "DHEA001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Dehydroepiandrosterone Sulphate (DHEAS)", code: "DHEAS001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Estradiol (E2)", code: "E2001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Follicle Stimulating Hormone (FSH)", code: "FSH001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Thyroxine (T4), Total", code: "T4TOTAL001", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Urine Glucose", code: "PF055", category: "Clinical Pathology", sampleType: "Urine", turnaroundHours: 8 },
  { name: "Urine Cotinine", code: "PF056", category: "Clinical Pathology", sampleType: "Urine", turnaroundHours: 24 },
  { name: "Prostate Biopsy", code: "PF057", category: "Histopathology", sampleType: "Tissue", turnaroundHours: 72 },
  { name: "Liver Biopsy", code: "PF058", category: "Histopathology", sampleType: "Tissue", turnaroundHours: 72 },
  { name: "Histopathology Skin Biopsy", code: "SKINBIO001", category: "Histopathology", sampleType: "Tissue", turnaroundHours: 72 },
  { name: "Histopathology Colonoscopy with Polypectomy Biopsy", code: "COLONBIO001", category: "Histopathology", sampleType: "Tissue", turnaroundHours: 72 },
  { name: "Fine Needle Aspiration Cytology (FNAC)", code: "FNAC001", category: "Cytology", sampleType: "FNAC / Aspiration", turnaroundHours: 24 },
  { name: "PAP Smear", code: "PAPSMEAR001", category: "Cytology", sampleType: "ThinPrep", turnaroundHours: 24 },
  { name: "Thyroid Antibody Profile", code: "PF059", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Luteinizing Hormone (LH)", code: "PF060", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "PAPP-A", code: "PF061", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Inhibin A", code: "PF062", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "Inhibin B", code: "PF063", category: "Endocrinology", sampleType: "Serum", turnaroundHours: 24 },
  { name: "MDMA Screen", code: "PF064", category: "Toxicology", sampleType: "Urine", turnaroundHours: 24 },
];

module.exports = { PATHOLOGY_REPORT_CATALOG };
