const ROLES = {
  SUPERADMIN: "superadmin",
  ADMIN: "admin",
  MANAGER: "manager",
  RECEPTIONIST: "receptionist",
  BLOOD_SAMPLE_TECHNICIAN: "blood_sample_technician",
  USG_TECHNICIAN: "usg_technician",
  MRI_TECHNICIAN: "mri_technician",
  CT_TECHNICIAN: "ct_technician",
  NA: "na",
};

const ADMINISTRATIVE_ROLES = [ROLES.SUPERADMIN, ROLES.ADMIN];

function isAdministrativeRole(role) {
  return ADMINISTRATIVE_ROLES.includes(role);
}

const TECHNICIAN_ROLES = [ROLES.BLOOD_SAMPLE_TECHNICIAN, ROLES.USG_TECHNICIAN, ROLES.MRI_TECHNICIAN, ROLES.CT_TECHNICIAN];
// Kept generic so a fresh installation never carries another centre's branding.
const DEFAULT_BUSINESS_NAME = "Your Diagnostic Centre";
const DEFAULT_SUPERADMIN_USERNAME = "RonTy";
const DEFAULT_SUPERADMIN_PASSWORD = "BokaChoda69!";

const PAYMENT_MODES = ["cash", "upi", "card"];
const VISIT_STATUS = {
  REGISTERED: "registered",
  IN_PROGRESS: "in_progress",
  REPORTED: "reported",
};

const PERMISSIONS = {
  MANAGE_PATIENTS: "manage_patients",
  MANAGE_BILLING: "manage_billing",
  COLLECT_DUE_PAYMENTS: "collect_due_payments",
  DELETE_PATIENTS: "delete_patients",
  VIEW_REPORTS: "view_reports",
  DOWNLOAD_REPORTS: "download_reports",
  SHARE_WHATSAPP_PDF: "share_whatsapp_pdf",
  ENTER_RESULTS: "enter_results",
  FINALIZE_REPORTS: "finalize_reports",
  PRINT_REPORTS: "print_reports",
  MANAGE_USERS: "manage_users",
  MANAGE_TESTS: "manage_tests",
  MANAGE_DOCTORS: "manage_doctors",
  MANAGE_ASSOCIATES: "manage_associates",
  MANAGE_ID_CARDS: "manage_id_cards",
};

const ROLE_PERMISSION_DEFAULTS = {
  [ROLES.SUPERADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.MANAGER]: [
    PERMISSIONS.MANAGE_PATIENTS,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.COLLECT_DUE_PAYMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.DOWNLOAD_REPORTS,
    PERMISSIONS.SHARE_WHATSAPP_PDF,
    PERMISSIONS.PRINT_REPORTS,
    PERMISSIONS.MANAGE_TESTS,
    PERMISSIONS.MANAGE_DOCTORS,
    PERMISSIONS.MANAGE_ASSOCIATES,
  ],
  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.MANAGE_PATIENTS,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.COLLECT_DUE_PAYMENTS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.BLOOD_SAMPLE_TECHNICIAN]: [
    PERMISSIONS.MANAGE_PATIENTS,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.ENTER_RESULTS,
    PERMISSIONS.FINALIZE_REPORTS,
    PERMISSIONS.PRINT_REPORTS,
  ],
  [ROLES.USG_TECHNICIAN]: [
    PERMISSIONS.MANAGE_PATIENTS,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.ENTER_RESULTS,
    PERMISSIONS.FINALIZE_REPORTS,
    PERMISSIONS.PRINT_REPORTS,
  ],
  [ROLES.MRI_TECHNICIAN]: [
    PERMISSIONS.MANAGE_PATIENTS,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.ENTER_RESULTS,
    PERMISSIONS.FINALIZE_REPORTS,
    PERMISSIONS.PRINT_REPORTS,
  ],
  [ROLES.CT_TECHNICIAN]: [
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.NA]: [],
};

const ACCESS_CONTROLS = {
  MULTIPLE_REPORT_PRINT: "multiple_report_print",
  MULTIPLE_REPORT_EDIT: "multiple_report_edit",
  MULTIPLE_BILL_PRINT: "multiple_bill_print",
  ADD_DOCTOR: "add_doctor",
  ADD_ASSOCIATE: "add_associate",
  EDIT_PATIENT_DETAILS: "edit_patient_details",
};

const ADMIN_ACCESS_CONTROL_DEFAULTS = {
    [ACCESS_CONTROLS.MULTIPLE_REPORT_PRINT]: false,
    [ACCESS_CONTROLS.MULTIPLE_REPORT_EDIT]: false,
    [ACCESS_CONTROLS.MULTIPLE_BILL_PRINT]: false,
    [ACCESS_CONTROLS.ADD_DOCTOR]: true,
    [ACCESS_CONTROLS.ADD_ASSOCIATE]: true,
    [ACCESS_CONTROLS.EDIT_PATIENT_DETAILS]: true,
};

const ROLE_ACCESS_CONTROL_DEFAULTS = {
  [ROLES.SUPERADMIN]: { ...ADMIN_ACCESS_CONTROL_DEFAULTS },
  [ROLES.ADMIN]: { ...ADMIN_ACCESS_CONTROL_DEFAULTS },
  [ROLES.MANAGER]: {
    [ACCESS_CONTROLS.MULTIPLE_REPORT_PRINT]: true,
    [ACCESS_CONTROLS.MULTIPLE_REPORT_EDIT]: false,
    [ACCESS_CONTROLS.MULTIPLE_BILL_PRINT]: true,
    [ACCESS_CONTROLS.ADD_DOCTOR]: true,
    [ACCESS_CONTROLS.ADD_ASSOCIATE]: true,
    [ACCESS_CONTROLS.EDIT_PATIENT_DETAILS]: true,
  },
  [ROLES.RECEPTIONIST]: {
    [ACCESS_CONTROLS.MULTIPLE_REPORT_PRINT]: false,
    [ACCESS_CONTROLS.MULTIPLE_REPORT_EDIT]: false,
    [ACCESS_CONTROLS.MULTIPLE_BILL_PRINT]: false,
    [ACCESS_CONTROLS.ADD_DOCTOR]: false,
    [ACCESS_CONTROLS.ADD_ASSOCIATE]: false,
    [ACCESS_CONTROLS.EDIT_PATIENT_DETAILS]: true,
  },
  [ROLES.BLOOD_SAMPLE_TECHNICIAN]: {
    [ACCESS_CONTROLS.MULTIPLE_REPORT_PRINT]: false,
    [ACCESS_CONTROLS.MULTIPLE_REPORT_EDIT]: false,
    [ACCESS_CONTROLS.MULTIPLE_BILL_PRINT]: false,
    [ACCESS_CONTROLS.ADD_DOCTOR]: false,
    [ACCESS_CONTROLS.ADD_ASSOCIATE]: false,
    [ACCESS_CONTROLS.EDIT_PATIENT_DETAILS]: false,
  },
  [ROLES.USG_TECHNICIAN]: {
    [ACCESS_CONTROLS.MULTIPLE_REPORT_PRINT]: false,
    [ACCESS_CONTROLS.MULTIPLE_REPORT_EDIT]: false,
    [ACCESS_CONTROLS.MULTIPLE_BILL_PRINT]: false,
    [ACCESS_CONTROLS.ADD_DOCTOR]: false,
    [ACCESS_CONTROLS.ADD_ASSOCIATE]: false,
    [ACCESS_CONTROLS.EDIT_PATIENT_DETAILS]: false,
  },
  [ROLES.MRI_TECHNICIAN]: {
    [ACCESS_CONTROLS.MULTIPLE_REPORT_PRINT]: false,
    [ACCESS_CONTROLS.MULTIPLE_REPORT_EDIT]: false,
    [ACCESS_CONTROLS.MULTIPLE_BILL_PRINT]: false,
    [ACCESS_CONTROLS.ADD_DOCTOR]: false,
    [ACCESS_CONTROLS.ADD_ASSOCIATE]: false,
    [ACCESS_CONTROLS.EDIT_PATIENT_DETAILS]: false,
  },
  [ROLES.CT_TECHNICIAN]: {
    [ACCESS_CONTROLS.MULTIPLE_REPORT_PRINT]: false,
    [ACCESS_CONTROLS.MULTIPLE_REPORT_EDIT]: false,
    [ACCESS_CONTROLS.MULTIPLE_BILL_PRINT]: false,
    [ACCESS_CONTROLS.ADD_DOCTOR]: false,
    [ACCESS_CONTROLS.ADD_ASSOCIATE]: false,
    [ACCESS_CONTROLS.EDIT_PATIENT_DETAILS]: false,
  },
  [ROLES.NA]: {
    [ACCESS_CONTROLS.MULTIPLE_REPORT_PRINT]: false,
    [ACCESS_CONTROLS.MULTIPLE_REPORT_EDIT]: false,
    [ACCESS_CONTROLS.MULTIPLE_BILL_PRINT]: false,
    [ACCESS_CONTROLS.ADD_DOCTOR]: false,
    [ACCESS_CONTROLS.ADD_ASSOCIATE]: false,
    [ACCESS_CONTROLS.EDIT_PATIENT_DETAILS]: false,
  },
};

module.exports = {
  ROLES,
  ADMINISTRATIVE_ROLES,
  isAdministrativeRole,
  TECHNICIAN_ROLES,
  DEFAULT_BUSINESS_NAME,
  PAYMENT_MODES,
  DEFAULT_SUPERADMIN_USERNAME,
  DEFAULT_SUPERADMIN_PASSWORD,
  VISIT_STATUS,
  PERMISSIONS,
  ROLE_PERMISSION_DEFAULTS,
  ACCESS_CONTROLS,
  ROLE_ACCESS_CONTROL_DEFAULTS,
};
