const fs = require('fs');
const sig = fs.readFileSync('e:/Web Development/lab-system/scratch/sig_b64.txt', 'utf8').trim();

let c = 'function escapeHtml(value) {\n';
c += '  return String(value ?? "")\n';
c += '    .replaceAll("&", "&amp;")\n';
c += '    .replaceAll("<", "&lt;")\n';
c += '    .replaceAll(">", "&gt;")\n';
c += '    .replaceAll(\'"\', "&quot;")\n';
c += '    .replaceAll("\'", "&#39;");\n';
c += '}\n\n';

c += 'function formatDateStr(date) {\n';
c += '  if (!date) return "-";\n';
c += '  const d = new Date(date);\n';
c += '  return d.toLocaleString(\'en-IN\', {\n';
c += '    day: \'2-digit\',\n';
c += '    month: \'short\',\n';
c += '    year: \'numeric\',\n';
c += '    hour: \'2-digit\',\n';
c += '    minute: \'2-digit\',\n';
c += '    hour12: true\n';
c += '  });\n';
c += '}\n\n';

c += 'function checkResultRange(value, rangeStr) {\n';
c += '  if (!value || !rangeStr) return { isAbnormal: false, colorClass: "" };\n';
c += '  const val = parseFloat(value.replace(/,/g, ""));\n';
c += '  if (isNaN(val)) return { isAbnormal: false, colorClass: "" };\n';
c += '  const parts = rangeStr.split("-").map(p => parseFloat(p.trim().replace(/,/g, "")));\n';
c += '  if (parts.length !== 2) return { isAbnormal: false, colorClass: "" };\n';
c += '  const [min, max] = parts;\n';
c += '  if (val < min) return { isAbnormal: true, colorClass: "low-val" };\n';
c += '  if (val > max) return { isAbnormal: true, colorClass: "high-val" };\n';
c += '  return { isAbnormal: false, colorClass: "" };\n';
c += '}\n\n';

c += 'function buildReportHtml(reportData) {\n';
c += '  const patientName = escapeHtml(reportData.patient.name);\n';
c += '  const billNo = escapeHtml(reportData.visit.bill_no);\n';
c += '  const age = escapeHtml(reportData.patient.age);\n';
c += '  const sex = escapeHtml(reportData.patient.gender);\n';
c += '  const doctorName = escapeHtml(reportData.doctor?.name || "Self");\n';
c += '  const doctorDegree = reportData.doctor?.specialization ? ` (${escapeHtml(reportData.doctor.specialization)})` : "";\n';
c += '  const billNoStr = String(reportData.visit.bill_no || "");\n';
c += '  const patientId = billNoStr.split("-").pop() || escapeHtml(reportData.patient.id);\n';
c += '  \n';
c += '  const registeredOn = formatDateStr(reportData.visit.created_at);\n';
c += '  const reportedOn = formatDateStr(reportData.report.finalized_at || new Date());\n\n';

c += '  const associateName = reportData.visit.associate_label || (reportData.associate ? reportData.associate.name : "");\n';
c += '  const sampleText = reportData.visit.sample_source === \'associate\' \n';
c += '    ? `SAMPLE COLLECTED BY: ${escapeHtml(associateName)}`\n';
c += '    : `SAMPLE COLLECTED AT: WE CARE DIAGNOSTICS CENTRE`;\n\n';

c += '  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(billNo + \'-\' + patientName)}`;\n';
c += '  const barcodeUrl = `https://bwipjs-api.metafloor.com/?bcid=code128&text=${encodeURIComponent(billNo)}&scale=2&height=10&includetext`;\n\n';

c += '  const testTitle = reportData.tests.length === 1 && (reportData.tests[0].name.toLowerCase().includes("cbc") || reportData.tests[0].name.toLowerCase().includes("complete blood count"))\n';
c += '    ? "COMPLETE BLOOD COUNT (CBC)"\n';
c += '    : "LABORATORY REPORT";\n\n';

c += '  return `\n';
c += '    <!DOCTYPE html>\n';
c += '    <html lang="en">\n';
c += '    <head>\n';
c += '      <meta charset="UTF-8">\n';
c += '      <style>\n';
c += '        @page {\n';
c += '          size: A3;\n';
c += '          margin: 0;\n';
c += '        }\n';
c += '        body { \n';
c += '          font-family: \'Times New Roman\', Times, serif; \n';
c += '          font-size: 18px;\n';
c += '          margin: 0; \n';
c += '          padding: 0;\n';
c += '          color: #000; \n';
c += '          line-height: 1.2;\n';
c += '          box-sizing: border-box;\n';
c += '          background: white;\n';
c += '          width: 297mm;\n';
c += '        }\n';
c += '        .blank-header {\n';
c += '          height: 3.5cm;\n';
c += '          width: 100%;\n';
c += '        }\n';
c += '        .main-content {\n';
c += '          padding: 0 1.5cm 1.5cm 1.5cm;\n';
c += '          min-height: calc(420mm - 3.5cm - 1.5cm);\n';
c += '          display: flex;\n';
c += '          flex-direction: column;\n';
c += '        }\n';
c += '        .header-table {\n';
c += '          width: 100%;\n';
c += '          border-top: 2px solid #000;\n';
c += '          border-bottom: 2px solid #000;\n';
c += '          border-collapse: collapse;\n';
c += '          margin-bottom: 20px;\n';
c += '        }\n';
c += '        .header-table td {\n';
c += '          vertical-align: top;\n';
c += '          padding: 10px;\n';
c += '          border-right: 1px solid #000;\n';
c += '        }\n';
c += '        .header-table td:last-child {\n';
c += '          border-right: none;\n';
c += '        }\n';
c += '        \n';
c += '        .patient-name { font-size: 26px; font-weight: bold; margin-bottom: 5px; text-transform: uppercase; }\n';
c += '        .info-row { margin-bottom: 4px; font-size: 18px; }\n';
c += '        \n';
c += '        .qr-img { width: 110px; height: 110px; display: block; margin: 0 auto; }\n';
c += '        .sample-text { font-size: 13px; text-align: center; margin-top: 5px; font-weight: bold; text-transform: uppercase; }\n';
c += '        .barcode-img { height: 35px; width: auto; margin-bottom: 5px; }\n\n';

c += '        .test-title { \n';
c += '          text-align: center; \n';
c += '          font-weight: bold; \n';
c += '          font-size: 24px; \n';
c += '          margin: 20px 0;\n';
c += '          text-decoration: underline;\n';
c += '        }\n';
c += '        \n';
c += '        table.results-table { width: 100%; border-collapse: collapse; flex-grow: 1; }\n';
c += '        table.results-table th { \n';
c += '          border-top: 2px solid #000; \n';
c += '          border-bottom: 2px solid #000; \n';
c += '          padding: 12px 5px; \n';
c += '          text-align: left; \n';
c += '          font-weight: bold;\n';
c += '          font-size: 19px;\n';
c += '        }\n';
c += '        table.results-table td { padding: 8px 5px; font-size: 18px; }\n';
c += '        .center { text-align: center; }\n';
c += '        .high-val, .low-val { font-weight: 900; text-decoration: underline; }\n';
c += '        \n';
c += '        .footer-note { margin-top: 30px; font-size: 14px; border-top: 1px solid #000; padding-top: 5px; font-style: italic; }\n';
c += '        .end-report { text-align: center; margin-top: 10px; font-weight: bold; border-top: 1px solid #eee; padding-top: 5px; }\n';
c += '        \n';
c += '        .signature-wrapper {\n';
c += '          margin-top: auto;\n';
c += '          padding-top: 40px;\n';
c += '          display: flex;\n';
c += '          justify-content: flex-end;\n';
c += '        }\n';
c += '        .signature-section {\n';
c += '          text-align: center;\n';
c += '          width: 250px;\n';
c += '        }\n';
c += '        .sig-image { \n';
c += '          width: 200px; \n';
c += '          height: auto; \n';
c += '          display: block; \n';
c += '          margin: 0 auto 5px auto;\n';
c += '        }\n';
c += '        .doc-name { font-weight: bold; font-size: 20px; margin: 0; }\n';
c += '        .doc-detail { font-size: 16px; margin: 0; }\n';
c += ' \n';
c += '        tr { page-break-inside: avoid; }\n';
c += '      </style>\n';
c += '    </head>\n';
c += '    <body>\n';
c += '      <div class="blank-header"></div>\n';
c += '      \n';
c += '      <div class="main-content">\n';
c += '        <table class="header-table">\n';
c += '          <tr>\n';
c += '            <td style="width: 40%;">\n';
c += '              <div class="patient-name">${patientName}</div>\n';
c += '              <div class="info-row">Age : ${age} Years</div>\n';
c += '              <div class="info-row">Sex : ${sex}</div>\n';
c += '              <div class="info-row">Ref. By: <strong>${doctorName}</strong>${doctorDegree}</div>\n';
c += '            </td>\n';
c += '            <td style="width: 25%; text-align: center;">\n';
c += '              <img src="${qrUrl}" class="qr-img" />\n';
c += '              <div class="sample-text">${sampleText}</div>\n';
c += '            </td>\n';
c += '            <td style="width: 35%; text-align: right; border-right: none;">\n';
c += '              <div class="info-row">PID : ${patientId}</div>\n';
c += '              <div style="margin-top: 10px;">\n';
c += '                <img src="${barcodeUrl}" class="barcode-img" />\n';
c += '              </div>\n';
c += '              <div class="info-row" style="font-size: 14px;">Registered on: ${registeredOn}</div>\n';
c += '              <div class="info-row" style="font-size: 14px;">Collected on: ${registeredOn}</div>\n';
c += '              <div class="info-row" style="font-size: 14px;">Reported on: ${reportedOn}</div>\n';
c += '            </td>\n';
c += '          </tr>\n';
c += '        </table>\n\n';

c += '        <div class="test-title">${testTitle}</div>\n\n';

c += '        <table class="results-table">\n';
c += '          <thead>\n';
c += '            <tr>\n';
c += '              <th style="width: 35%">INVESTIGATION</th>\n';
c += '              <th class="center" style="width: 20%">RESULT</th>\n';
c += '              <th class="center" style="width: 20%">UNIT</th>\n';
c += '              <th class="center" style="width: 25%">REFERENCE RANGE</th>\n';
  c += '            </tr>\n';
  c += '          </thead>\n';
  c += '          <tbody>\n';
  c += '            ${reportData.tests.flatMap(test => {\n';
  c += '              const rows = test.parameters.map(param => {\n';
  c += '                if (param.parameter_name === "Differential Leucocyte Count") {\n';
  c += '                  return `<tr><td colspan="4" style="font-weight: bold; padding-top: 20px; font-size: 20px;">${escapeHtml(param.parameter_name)}</td></tr>`;\n';
  c += '                }\n';
  c += '                const { isAbnormal, colorClass } = checkResultRange(param.value, param.normal_range);\n';
  c += '                const valDisplay = isAbnormal ? `<span class="${colorClass}">${escapeHtml(param.value || "-")}</span>` : escapeHtml(param.value || "-");\n';
  c += '                \n';
  c += '                const needsIndentation = [\n';
  c += '                  "Neutrophils", "Lymphocytes", "Eosinophils", "Monocytes", "Basophils",\n';
  c += '                  "Neutrophil", "Lymphocyte", "Eosinophil", "Monocyte", "Basophil",\n';
  c += '                ].some(s => param.parameter_name.includes(s));\n';
  c += '                const padding = needsIndentation ? \'30px\' : \'0\';\n';
  c += '                \n';
  c += '                return `\n';
  c += '                  <tr>\n';
  c += '                    <td style="padding-left: ${padding}">${escapeHtml(param.parameter_name)}</td>\n';
  c += '                    <td class="center" style="font-weight: ${isAbnormal ? \'bold\' : \'normal\'}">${valDisplay}</td>\n';
  c += '                    <td class="center">${escapeHtml(param.unit || "")}</td>\n';
  c += '                    <td class="center">${escapeHtml(param.normal_range || "-")}</td>\n';
  c += '                  </tr>\n';
  c += '                `;\n';
  c += '              });\n';
  c += '              return rows;\n';
  c += '            }).join(\'\')}\n';
  c += '          </tbody>\n';
  c += '        </table>\n\n';

  c += '        <div class="footer-note">\n';
  c += '          Note: This is a computer generated report. Clinical correlation is recommended for final diagnosis. Results pertain to the sample tested.\n';
  c += '        </div>\n';
  c += '        \n';
  c += '        <div class="end-report">*** End of report ***</div>\n\n';

  c += '        <div class="signature-wrapper">\n';
  c += '          <div class="signature-section">\n';
  c += '            <img src="data:image/jpeg;base64,' + sig + '" class="sig-image" />\n';
  c += '            <p class="doc-name">Dr. Arun Kumar Biswas</p>\n';
  c += '            <p class="doc-detail">MBBS, MD (Path.)</p>\n';
  c += '            <p class="doc-detail">Consultant Pathologist</p>\n';
  c += '            <p class="doc-detail">Regd. No.- 58516</p>\n';
  c += '          </div>\n';
  c += '        </div>\n';
  c += '      </div>\n';
  c += '    </body>\n';
  c += '    </html>\n';
  c += '  `;\n';
  c += '}\n\n';

  c += 'module.exports = { buildReportHtml };\n';

fs.writeFileSync('e:/Web Development/lab-system/src/utils/reportFormatter.js', c);
console.log('Successfully wrote reportFormatter.js');
