const fs = require('fs');
const sig = fs.readFileSync('e:/Web Development/lab-system/scratch/sig_b64.txt', 'utf8').trim();

const lines = [
  'function escapeHtml(value) {',
  '  return String(value ?? "")',
  '    .replaceAll("&", "&amp;")',
  '    .replaceAll("<", "&lt;")',
  '    .replaceAll(">", "&gt;")',
  '    .replaceAll(\'"\', "&quot;")',
  '    .replaceAll("\'", "&#39;");',
  '}',
  '',
  'function formatDateStr(date) {',
  '  if (!date) return "-";',
  '  const d = new Date(date);',
  '  return d.toLocaleString(\'en-IN\', {',
  '    day: \'2-digit\',',
  '    month: \'short\',',
  '    year: \'numeric\',',
  '    hour: \'2-digit\',',
  '    minute: \'2-digit\',',
  '    hour12: true',
  '  });',
  '}',
  '',
  'function checkResultRange(value, rangeStr) {',
  '  if (!value || !rangeStr) return { isAbnormal: false, colorClass: "" };',
  '  const val = parseFloat(value.replace(/,/g, ""));',
  '  if (isNaN(val)) return { isAbnormal: false, colorClass: "" };',
  '  const parts = rangeStr.split("-").map(p => parseFloat(p.trim().replace(/,/g, "")));',
  '  if (parts.length !== 2) return { isAbnormal: false, colorClass: "" };',
  '  const [min, max] = parts;',
  '  if (val < min) return { isAbnormal: true, colorClass: "low-val" };',
  '  if (val > max) return { isAbnormal: true, colorClass: "high-val" };',
  '  return { isAbnormal: false, colorClass: "" };',
  '}',
  '',
  'function buildReportHtml(reportData) {',
  '  const patientName = escapeHtml(reportData.patient.name);',
  '  const billNo = escapeHtml(reportData.visit.bill_no);',
  '  const age = escapeHtml(reportData.patient.age);',
  '  const sex = escapeHtml(reportData.patient.gender);',
  '  const doctorName = escapeHtml(reportData.doctor?.name || "Self");',
  '  const doctorDegree = reportData.doctor?.specialization ? ` (${escapeHtml(reportData.doctor.specialization)})` : "";',
  '  const billNoStr = String(reportData.visit.bill_no || "");',
  '  const patientId = billNoStr.split("-").pop() || escapeHtml(reportData.patient.id);',
  '  ',
  '  const registeredOn = formatDateStr(reportData.visit.created_at);',
  '  const reportedOn = formatDateStr(reportData.report.finalized_at || new Date());',
  '',
  '  const associateName = reportData.visit.associate_label || (reportData.associate ? reportData.associate.name : "");',
  '  const sampleText = reportData.visit.sample_source === \'associate\' ',
  '    ? `SAMPLE COLLECTED BY: ${escapeHtml(associateName)}`',
  '    : `SAMPLE COLLECTED AT: WE CARE DIAGNOSTICS CENTRE`;',
  '',
  '  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(billNo + \'-\' + patientName)}`;',
  '  const barcodeUrl = `https://bwipjs-api.metafloor.com/?bcid=code128&text=${encodeURIComponent(billNo)}&scale=2&height=10&includetext`;',
  '',
  '  const testTitle = reportData.tests.length === 1 && (reportData.tests[0].name.toLowerCase().includes("cbc") || reportData.tests[0].name.toLowerCase().includes("complete blood count"))',
  '    ? "COMPLETE BLOOD COUNT (CBC)"',
  '    : "LABORATORY REPORT";',
  '',
  '  return `',
  '    <!DOCTYPE html>',
  '    <html lang="en">',
  '    <head>',
  '      <meta charset="UTF-8">',
  '      <style>',
  '        @page {',
  '          size: A3;',
  '          margin: 0;',
  '        }',
  '        body { ',
  '          font-family: \'Times New Roman\', Times, serif; ',
  '          font-size: 18px;',
  '          margin: 0; ',
  '          padding: 0;',
  '          color: #000; ',
  '          line-height: 1.2;',
  '          box-sizing: border-box;',
  '          background: white;',
  '          width: 297mm;',
  '        }',
  '        .blank-header {',
  '          height: 3.5cm;',
  '          width: 100%;',
  '        }',
  '        .main-content {',
  '          padding: 0 1.5cm 1.5cm 1.5cm;',
  '          min-height: calc(420mm - 3.5cm - 1.5cm);',
  '          display: flex;',
  '          flex-direction: column;',
  '        }',
  '        .header-table {',
  '          width: 100%;',
  '          border-top: 2px solid #000;',
  '          border-bottom: 2px solid #000;',
  '          border-collapse: collapse;',
  '          margin-bottom: 20px;',
  '        }',
  '        .header-table td {',
  '          vertical-align: top;',
  '          padding: 10px;',
  '          border-right: 1px solid #000;',
  '        }',
  '        .header-table td:last-child {',
  '          border-right: none;',
  '        }',
  '        ',
  '        .patient-name { font-size: 26px; font-weight: bold; margin-bottom: 5px; text-transform: uppercase; }',
  '        .info-row { margin-bottom: 4px; font-size: 18px; }',
  '        ',
  '        .qr-img { width: 110px; height: 110px; display: block; margin: 0 auto; }',
  '        .sample-text { font-size: 13px; text-align: center; margin-top: 5px; font-weight: bold; text-transform: uppercase; }',
  '        .barcode-img { height: 35px; width: auto; margin-bottom: 5px; }',
  '',
  '        .test-title { ',
  '          text-align: center; ',
  '          font-weight: bold; ',
  '          font-size: 24px; ',
  '          margin: 20px 0;',
  '          text-decoration: underline;',
  '        }',
  '        ',
  '        table.results-table { width: 100%; border-collapse: collapse; flex-grow: 1; }',
  '        table.results-table th { ',
  '          border-top: 2px solid #000; ',
  '          border-bottom: 2px solid #000; ',
  '          padding: 12px 5px; ',
  '          text-align: left; ',
  '          font-weight: bold;',
  '          font-size: 19px;',
  '        }',
  '        table.results-table td { padding: 8px 5px; font-size: 18px; }',
  '        .center { text-align: center; }',
  '        .high-val, .low-val { font-weight: 900; text-decoration: underline; }',
  '        ',
  '        .footer-note { margin-top: 30px; font-size: 14px; border-top: 1px solid #000; padding-top: 5px; font-style: italic; }',
  '        .end-report { text-align: center; margin-top: 10px; font-weight: bold; border-top: 1px solid #eee; padding-top: 5px; }',
  '        ',
  '        .signature-wrapper {',
  '          margin-top: auto;',
  '          padding-top: 40px;',
  '          display: flex;',
  '          justify-content: flex-end;',
  '        }',
  '        .signature-section {',
  '          text-align: center;',
  '          width: 250px;',
  '        }',
  '        .sig-image { ',
  '          width: 200px; ',
  '          height: auto; ',
  '          display: block; ',
  '          margin: 0 auto 5px auto;',
  '        }',
  '        .doc-name { font-weight: bold; font-size: 20px; margin: 0; }',
  '        .doc-detail { font-size: 16px; margin: 0; }',
  ' ',
  '        tr { page-break-inside: avoid; }',
  '      </style>',
  '    </head>',
  '    <body>',
  '      <div class="blank-header"></div>',
  '      ',
  '      <div class="main-content">',
  '        <table class="header-table">',
  '          <tr>',
  '            <td style="width: 40%;">',
  '              <div class="patient-name">${patientName}</div>',
  '              <div class="info-row">Age : ${age} Years</div>',
  '              <div class="info-row">Sex : ${sex}</div>',
  '              <div class="info-row">Ref. By: <strong>${doctorName}</strong>${doctorDegree}</div>',
  '            </td>',
  '            <td style="width: 25%; text-align: center;">',
  '              <img src="${qrUrl}" class="qr-img" />',
  '              <div class="sample-text">${sampleText}</div>',
  '            </td>',
  '            <td style="width: 35%; text-align: right; border-right: none;">',
  '              <div class="info-row">PID : ${patientId}</div>',
  '              <div style="margin-top: 10px;">',
  '                <img src="${barcodeUrl}" class="barcode-img" />',
  '              </div>',
  '              <div class="info-row" style="font-size: 14px;">Registered on: ${registeredOn}</div>',
  '              <div class="info-row" style="font-size: 14px;">Collected on: ${registeredOn}</div>',
  '              <div class="info-row" style="font-size: 14px;">Reported on: ${reportedOn}</div>',
  '            </td>',
  '          </tr>',
  '        </table>',
  '',
  '        <div class="test-title">${testTitle}</div>',
  '',
  '        <table class="results-table">',
  '          <thead>',
  '            <tr>',
  '              <th style="width: 35%">INVESTIGATION</th>',
  '              <th class="center" style="width: 20%">RESULT</th>',
  '              <th class="center" style="width: 20%">UNIT</th>',
  '              <th class="center" style="width: 25%">REFERENCE RANGE</th>',
  '            </tr>',
  '          </thead>',
  '          <tbody>',
  '            ${reportData.tests.flatMap(test => {',
  '              const rows = test.parameters.map(param => {',
  '                if (param.parameter_name === "Differential Leucocyte Count") {',
  '                  return `<tr><td colspan="4" style="font-weight: bold; padding-top: 20px; font-size: 20px;">${escapeHtml(param.parameter_name)}</td></tr>`;',
  '                }',
  '                const { isAbnormal, colorClass } = checkResultRange(param.value, param.normal_range);',
  '                const valDisplay = isAbnormal ? `<span class="${colorClass}">${escapeHtml(param.value || "-")}</span>` : escapeHtml(param.value || "-");',
  '                ',
  '                const needsIndentation = [',
  '                  "Neutrophils", "Lymphocytes", "Eosinophils", "Monocytes", "Basophils",',
  '                  "Neutrophil", "Lymphocyte", "Eosinophil", "Monocyte", "Basophil"',
  '                ].some(s => param.parameter_name.includes(s));',
  '                const padding = needsIndentation ? \'30px\' : \'0\';',
  '                ',
  '                return `',
  '                  <tr>',
  '                    <td style="padding-left: ${padding}">${escapeHtml(param.parameter_name)}</td>',
  '                    <td class="center" style="font-weight: ${isAbnormal ? \'bold\' : \'normal\'}">${valDisplay}</td>',
  '                    <td class="center">${escapeHtml(param.unit || "")}</td>',
  '                    <td class="center">${escapeHtml(param.normal_range || "-")}</td>',
  '                  </tr>',
  '                `;',
  '              });',
  '              return rows;',
  '            }).join(\'\')}',
  '          </tbody>',
  '        </table>',
  '',
  '        <div class="footer-note">',
  '          Note: This is a computer generated report. Clinical correlation is recommended for final diagnosis. Results pertain to the sample tested.',
  '        </div>',
  '        ',
  '        <div class="end-report">*** End of report ***</div>',
  '',
  '        <div class="signature-wrapper">',
  '          <div class="signature-section">',
  '            <img src="data:image/jpeg;base64,' + sig + '" class="sig-image" />',
  '            <p class="doc-name">Dr. Arun Kumar Biswas</p>',
  '            <p class="doc-detail">MBBS, MD (Path.)</p>',
  '            <p class="doc-detail">Consultant Pathologist</p>',
  '            <p class="doc-detail">Regd. No.- 58516</p>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </body>',
  '    </html>',
  '  `;',
  '}',
  '',
  'module.exports = { buildReportHtml };'
];

fs.writeFileSync('e:/Web Development/lab-system/src/utils/reportFormatter.js', lines.join('\\n'));
console.log('Successfully wrote reportFormatter.js');
