const fs = require('fs');
const sig = fs.readFileSync('e:/Web Development/lab-system/scratch/sig_b64.txt', 'utf8').trim();

let c = 'function escapeHtml(value) {\n';
c += '  return String(value ?? "")\n';
c += '    .replaceAll("&", "&amp;")\n';
c += '    .replaceAll("<", "&lt;")\n';
c += '    .replaceAll(">", "&gt;")\n';
c += '    .replaceAll(\'"\', "&quot;")\n';
c += '    .replaceAll("\'", "&#39;");\n';
c += '}\n\n';

c += 'function formatDateStr(date) {\n';
c += '  if (!date) return "-";\n';
c += '  const d = new Date(date);\n';
c += '  return d.toLocaleString(\'en-IN\', {\n';
c += '    day: \'2-digit\',\n';
c += '    month: \'short\',\n';
c += '    year: \'numeric\',\n';
c += '    hour: \'2-digit\',\n';
c += '    minute: \'2-digit\',\n';
c += '    hour12: true\n';
  c += '  });\n';
  c += '}\n\n';

  c += 'function checkResultRange(value, rangeStr) {\n';
  c += '  if (!value || !rangeStr) return { isAbnormal: false, colorClass: "" };\n';
  c += '  const val = parseFloat(value.replace(/,/g, ""));\n';
  c += '  if (isNaN(val)) return { isAbnormal: false, colorClass: "" };\n\n';
  c += '  const rangeParts = rangeStr.split(/[,;]/);\n';
  c += '  for (let part of rangeParts) {\n';
  c += '    const match = part.match(/(\\d+\\.?\\d*)\\s*-\\s*(\\d+\\.?\\d*)/);\n';
  c += '    if (match) {\n';
  c += '      const min = parseFloat(match[1]);\n';
  c += '      const max = parseFloat(match[2]);\n';
  c += '      if (val < min) return { isAbnormal: true, colorClass: "low-val" };\n';
  c += '      if (val > max) return { isAbnormal: true, colorClass: "high-val" };\n';
  c += '      return { isAbnormal: false, colorClass: "" };\n';
  c += '    }\n';
  c += '  }\n';
  c += '  return { isAbnormal: false, colorClass: "" };\n';
  c += '}\n\n';

  c += 'function buildReportHtml(reportData) {\n';
  c += '  const patientName = escapeHtml(reportData.patient.name);\n';
  c += '  const billNo = escapeHtml(reportData.visit.bill_no);\n';
  c += '  const age = escapeHtml(reportData.patient.age);\n';
  c += '  const sex = escapeHtml(reportData.patient.gender);\n';
  c += '  const doctorName = escapeHtml(reportData.doctor?.name || "Self");\n';
  c += '  const billNoStr = String(reportData.visit.bill_no || "");\n';
  c += '  const patientId = billNoStr.split("-").pop() || escapeHtml(reportData.patient.id);\n';
  c += '  \n';
  c += '  const registeredOn = formatDateStr(reportData.visit.created_at);\n';
  c += '  const reportedOn = formatDateStr(reportData.report.finalized_at || new Date());\n\n';

  c += '  const associateName = reportData.visit.associate_label || (reportData.associate ? reportData.associate.name : "");\n';

  c += '  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(billNo + \'-\' + patientName)}`;\n';
  c += '  const barcodeUrl = `https://bwipjs-api.metafloor.com/?bcid=code128&text=${encodeURIComponent(billNo)}&scale=2&height=10&includetext`;\n\n';

  c += '  return `\n';
  c += '    <!DOCTYPE html>\n';
  c += '    <html lang="en">\n';
  c += '    <head>\n';
  c += '      <meta charset="UTF-8">\n';
  c += '      <style>\n';
  c += '        @page {\n';
  c += '          size: A3;\n';
  c += '          margin: 0;\n';
  c += '        }\n';
  c += '        body { \n';
  c += '          font-family: \'Times New Roman\', Times, serif; \n';
  c += '          font-size: 18px;\n';
  c += '          margin: 0; \n';
  c += '          padding: 0;\n';
  c += '          color: #000; \n';
  c += '          line-height: 1.2;\n';
  c += '          box-sizing: border-box;\n';
  c += '          background: white;\n';
  c += '          width: 297mm;\n';
  c += '        }\n';
  c += '        .blank-header {\n';
  c += '          height: 3.5cm;\n';
  c += '          width: 100%;\n';
  c += '        }\n';
  c += '        .main-content {\n';
  c += '          padding: 0 1.5cm 1.5cm 1.5cm;\n';
  c += '          min-height: calc(420mm - 3.5cm - 1.5cm);\n';
  c += '          display: flex;\n';
  c += '          flex-direction: column;\n';
  c += '        }\n';
  c += '        .header-table {\n';
  c += '          width: 100%;\n';
  c += '          border-top: 2px solid #000;\n';
  c += '          border-bottom: 2px solid #000;\n';
  c += '          border-collapse: collapse;\n';
  c += '          margin-bottom: 20px;\n';
  c += '        }\n';
  c += '        .header-table td {\n';
  c += '          vertical-align: top;\n';
  c += '          padding: 10px;\n';
  c += '          border-right: 1px solid #aaa;\n';
  c += '        }\n';
  c += '        .header-table td:last-child {\n';
  c += '          border-right: none;\n';
  c += '        }\n';
  c += '        \n';
  c += '        .patient-name { font-size: 26px; font-weight: bold; margin-bottom: 10px; text-transform: uppercase; }\n';
  c += '        .info-row { margin-bottom: 5px; font-size: 18px; display: flex; }\n';
  c += '        .info-label { width: 60px; color: #333; }\n';
  c += '        .info-colon { width: 15px; }\n';
  c += '        \n';
  c += '        .qr-img { width: 85px; height: 85px; margin-top: 5px; }\n';
  c += '        .barcode-img { height: 45px; width: auto; margin-bottom: 8px; }\n\n';

  c += '        .dept-title { \n';
  c += '          text-align: center; \n';
  c += '          font-weight: bold; \n';
  c += '          font-size: 22px; \n';
  c += '          margin: 10px 0;\n';
  c += '          text-decoration: underline;\n';
  c += '          text-transform: uppercase;\n';
  c += '        }\n';
  c += '        \n';
  c += '        table.results-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }\n';
  c += '        table.results-table th { \n';
  c += '          border-top: 2px solid #000; \n';
  c += '          border-bottom: 2px solid #000; \n';
  c += '          padding: 8px 5px; \n';
  c += '          text-align: left; \n';
  c += '          font-weight: bold;\n';
  c += '          font-size: 19px;\n';
  c += '        }\n';
  c += '        table.results-table td { padding: 6px 5px; font-size: 18px; vertical-align: top; }\n';
  c += '        .center { text-align: center; }\n';
  c += '        .high-val, .low-val { font-weight: 900; text-decoration: underline; }\n';
  c += '        \n';
  c += '        .group-header { font-weight: bold; text-decoration: underline; padding-top: 15px !important; padding-bottom: 5px !important; font-size: 19px; }\n';
  c += '        .sub-param { padding-left: 30px !important; }\n';
  c += '        \n';
  c += '        .footer-note { margin-top: auto; font-size: 14px; border-top: 1px solid #000; padding-top: 5px; font-style: italic; }\n';
  c += '        .end-report { text-align: center; margin-top: 5px; font-weight: bold; padding-bottom: 10px; }\n';
  c += '        \n';
  c += '        .signature-wrapper {\n';
  c += '          display: flex;\n';
  c += '          justify-content: flex-end;\n';
  c += '          padding-bottom: 20px;\n';
  c += '        }\n';
  c += '        .signature-section {\n';
  c += '          text-align: center;\n';
  c += '          width: 250px;\n';
  c += '        }\n';
  c += '        .sig-image { \n';
  c += '          width: 180px; \n';
  c += '          height: auto; \n';
  c += '          display: block; \n';
  c += '          margin: 0 auto 5px auto;\n';
  c += '        }\n';
  c += '        .doc-name { font-weight: bold; font-size: 20px; margin: 0; color: #1a237e; }\n';
  c += '        .doc-detail { font-size: 16px; margin: 0; color: #1a237e; }\n';
  c += ' \n';
  c += '        tr { page-break-inside: avoid; }\n';
  c += '      </style>\n';
  c += '    </head>\n';
  c += '    <body>\n';
  c += '      <div class="blank-header"></div>\n';
  c += '      \n';
  c += '      <div class="main-content">\n';
  c += '        <table class="header-table">\n';
  c += '          <tr>\n';
  c += '            <td style="width: 40%;">\n';
  c += '              <div class="patient-name">${patientName}</div>\n';
  c += '              <div style="display: flex; align-items: flex-start; justify-content: space-between;">\n';
  c += '                <div style="flex-grow: 1;">\n';
  c += '                  <div class="info-row"><span class="info-label">Age</span><span class="info-colon">:</span> ${age} Years</div>\n';
  c += '                  <div class="info-row"><span class="info-label">Sex</span><span class="info-colon">:</span> ${sex.charAt(0).toUpperCase() + sex.slice(1).toLowerCase()}</div>\n';
  c += '                  <div class="info-row"><span class="info-label">PID</span><span class="info-colon">:</span> ${patientId}</div>\n';
  c += '                </div>\n';
  c += '                <div style="padding-right: 15px;">\n';
  c += '                  <img src="${qrUrl}" class="qr-img" />\n';
  c += '                </div>\n';
  c += '              </div>\n';
  c += '            </td>\n';
  c += '            <td style="width: 30%;">\n';
  c += '              <div style="margin-bottom: 12px;">\n';
  c += '                <strong style="font-size: 17px; display: block; margin-bottom: 4px;">Sample Collected At:</strong>\n';
  c += '                <span style="font-size: 16px; color: #222; line-height: 1.4;">${escapeHtml(associateName || "City Main Lab")}</span>\n';
  c += '              </div>\n';
  c += '              <div style="margin-top: 15px;">\n';
  c += '                <span style="font-size: 17px;">Ref. By:</span> <strong style="font-size: 18px;">${doctorName}</strong>\n';
  c += '                ${reportData.doctor?.specialization ? `<div style="font-size: 14px; color: #444; margin-top: 2px;">${escapeHtml(reportData.doctor.specialization)}</div>` : \'\'}\n';
  c += '              </div>\n';
  c += '            </td>\n';
  c += '            <td style="width: 30%; border-right: none;">\n';
  c += '              <div style="text-align: right; padding-right: 10px;">\n';
  c += '                <img src="${barcodeUrl}" class="barcode-img" />\n';
  c += '                <div class="info-row" style="justify-content: flex-end; font-size: 15px;"><span style="width: 100px; text-align: left;">Registered on:</span> <span style="font-weight: 500;">${registeredOn}</span></div>\n';
  c += '                <div class="info-row" style="justify-content: flex-end; font-size: 15px;"><span style="width: 100px; text-align: left;">Collected on:</span> <span style="font-weight: 500;">${registeredOn}</span></div>\n';
  c += '                <div class="info-row" style="justify-content: flex-end; font-size: 15px;"><span style="width: 100px; text-align: left;">Reported on:</span> <span style="font-weight: 500;">${reportedOn}</span></div>\n';
  c += '              </div>\n';
  c += '            </td>\n';
  c += '          </tr>\n';
  c += '        </table>\n\n';

  c += '        <div class="dept-title">DEPARTMENT OF HAEMATOLOGY</div>\n\n';

  c += '        <table class="results-table">\n';
  c += '          <thead>\n';
  c += '            <tr>\n';
  c += '              <th style="width: 40%">Test Description</th>\n';
  c += '              <th class="center" style="width: 15%">Result Value</th>\n';
  c += '              <th class="center" style="width: 15%">Unit</th>\n';
  c += '              <th style="width: 30%">Bio. Ref. Interval</th>\n';
  c += '            </tr>\n';
  c += '          </thead>\n';
  c += '          <tbody>\n';
  c += '            ${reportData.tests.flatMap(test => {\n';
  c += '              return test.parameters.map(param => {\n';
  c += '                const isHeader = [\n';
  c += '                  "CBC (Complete Blood Count)",\n';
  c += '                  "TLC (Total Leukocytes Count)",\n';
  c += '                  "DLC (Differential Leukocytes Count)",\n';
  c += '                  "ESR (Erythrocyte Sedimentation Rate)"\n';
  c += '                ].includes(param.parameter_name);\n\n';

  c += '                if (isHeader) {\n';
  c += '                  return `<tr><td colspan="4" class="group-header">${escapeHtml(param.parameter_name)}</td></tr>`;\n';
  c += '                }\n\n';

  c += '                const { isAbnormal, colorClass } = checkResultRange(param.value, param.normal_range);\n';
  c += '                const valDisplay = isAbnormal ? `<span class="${colorClass}">${escapeHtml(param.value || "-")}</span>` : escapeHtml(param.value || "-");\n';
  c += '                \n';
  c += '                const isSubParam = [\n';
  c += '                  "Erythrocytes", "Leukocytes",\n';
  c += '                  "Neutrophils", "Lymphocytes", "Monocytes", "Eosinophils", "Basophils",\n';
  c += '                  "1st Hr. (Westegren Method)"\n';
  c += '                ].includes(param.parameter_name);\n';
  c += '                \n';
  c += '                const nameClass = isSubParam ? \'sub-param\' : \'\';\n';
  c += '                \n';
  c += '                if (param.parameter_name === "Peripheral Smear") {\n';
  c += '                   const res = param.value ? escapeHtml(param.value).replace(/\\n/g, "<br>") : "";\n';
  c += '                   return `\n';
  c += '                    <tr><td colspan="4" style="font-weight: bold; padding-top: 10px;">Peripheral Smear</td></tr>\n';
  c += '                    ${res ? `<tr><td colspan="4" style="padding-left: 10px; padding-bottom: 5px;">${res}</td></tr>` : ""}\n';
  c += '                    <tr><td colspan="4" style="font-size: 14px; padding-left: 10px;">* Methodology: Done by Hematology Analyzer</td></tr>\n';
  c += '                    <tr><td colspan="4" style="font-size: 14px; padding-left: 10px; font-style: italic; padding-bottom: 10px;">Note: If there is any clinical suspicion, the test can be repeated at the cost of Laboratory. Please correlate with the clinical conditions.</td></tr>\n';
  c += '                  `;\n';
  c += '                }\n\n';

  c += '                return `\n';
  c += '                  <tr>\n';
  c += '                    <td class="${nameClass}">${escapeHtml(param.parameter_name)}</td>\n';
  c += '                    <td class="center" style="font-weight: ${isAbnormal ? \'bold\' : \'normal\'}">${valDisplay}</td>\n';
  c += '                    <td class="center">${escapeHtml(param.unit || "")}</td>\n';
  c += '                    <td style="font-size: 15px;">${escapeHtml(param.normal_range || "-")}</td>\n';
  c += '                  </tr>\n';
  c += '                `;\n';
  c += '              });\n';
  c += '            }).join(\'\')}\n';
  c += '          </tbody>\n';
  c += '        </table>\n\n';

  c += '        <div class="end-report">:: End of Report ::</div>\n\n';

  c += '        <div class="footer-note">\n';
  c += '          Madhuban (Near Purna Cinema), Kalna - 713409, Purba Bardhaman, T: 03454-257571, M: 78721 22767 / 94343 33750 / 94331 20433, E: wecareprabir@gmail.com\n';
  c += '          <br><span style="font-size: 11px;">This laboratory finding(s) is / are only for referral guidance and dependent on assay procedure(s), equipment(s) & chemical(s) used and quality of sample(s) as applicable. The final diagnosis should be made with the co-relation of other clinical findings. For any kind of technical query relevant to this report, please contact us immediately. Patient identity is not verified for pathology sample(s) collected from outside. This report is not valid for medico-legal purpose.</span>\n';
  c += '        </div>\n\n';

  c += '        <div class="signature-wrapper">\n';
  c += '          <div class="signature-section">\n';
  c += '            <img src="data:image/jpeg;base64,' + sig + '" class="sig-image" />\n';
  c += '            <p class="doc-name">Dr. Arun Kumar Biswas</p>\n';
  c += '            <p class="doc-detail">MBBS, MD (Path.)</p>\n';
  c += '            <p class="doc-detail">Consultant Pathologist</p>\n';
  c += '            <p class="doc-detail">Regd. No.- 58516</p>\n';
  c += '          </div>\n';
  c += '        </div>\n';
  c += '      </div>\n';
  c += '    </body>\n';
  c += '    </html>\n';
  c += '  `;\n';
  c += '}\n\n';

  c += 'module.exports = { buildReportHtml };\n';

fs.writeFileSync('e:/Web Development/lab-system/src/utils/reportFormatter.js', c);
console.log('Successfully wrote reportFormatter.js');
